### ISSUE TITLE
🐞[BUG]: Ivy build error

### ISSUE THREAD

**Issue by C1E1S1T** [ngxs/store#1165] opened 2019-07-20 01:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... 
</code></pre>

## Current behavior

Angular cli can not compiled with Ivy (ng serve works):
node --max-old-space-size=8192 ./node_modules/@angular/cli/bin/ng build --prod
```
ERROR in ./src/app/authenticated-users/inventory/inventory.module.ts 49:21-41
"export 'NgxsFeatureModule' (imported as 'i1') was not found in '@ngxs/store'
ERROR in ./src/app/authenticated-users/cashier/cashier.module.ts 49:24-44
"export 'NgxsFeatureModule' (imported as 'i1') was not found in '@ngxs/store'
ERROR in ./src/store/store.module.ts 31:79-96
"export 'NgxsRootModule' (imported as 'i1') was not found in '@ngxs/store'
```

## Expected behavior

Angular cli can compiled with Ivy

## Environment

<pre><code>
Libs:
- @angular/core version: ^8.2.0-next.1
- @ngxs/store version: ^3.3.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Opera 62.0.3331.72
 
For Tooling issues:
- Node version:  v12.6.0.  
- Platform: Linux Ubuntu 16.4

Others:

Azure
</code></pre>

**Comment by splincode** [comment] 2019-07-20 05:11
Show stackblitz or repo example

**Comment by markwhitfeld** [comment] 2019-07-23 08:24
This issue has been reported to the angular team: https://github.com/angular/angular/issues/31791

PS. This is not really possible to reproduce in StackBlitz so @arturovt made a repo here:
https://github.com/arturovt/ivy-ngxs-repro

**Comment by ErazerBrecht** [comment] 2019-07-27 18:28
We are currently trying Ivy out in our codebase and for now it seems that ngxs 3.4.X works with Ivy.

**Comment by arturovt** [comment] 2019-07-27 19:04
@ErazerBrecht This works if you target `es2015`, but it doesn't work with `es5`.

**Comment by splincode** [comment] 2019-07-30 21:14
Router plugin does not support with Ivy

![image](https://user-images.githubusercontent.com/12021443/62165900-2017b880-b328-11e9-8aee-8b63f0ae16d4.png)

**Comment by splincode** [comment] 2019-08-01 19:21
https://github.com/angular/angular-cli/issues/15225

**Comment by workfel** [comment] 2019-08-08 11:24
I have the same problem than @splincode for Router plugin. 
All Ngxs package are `3.5.0` .
Typescript `3.5.3` .
All Angular `8,2,0`

**Comment by Koslun** [comment] 2019-08-23 01:00
Referenced Angular CLI issue seems to be resolved.

Anyone checked Ivy Compiler Compatibility with latest version of Angular 8 or 9? See that there has been some effort to validate all existing popular angular libraries here: https://github.com/mgechev/ngcc-validation. Where NGXS does seem to be included. Can't really find any confirmation that things are working, just absence of existing issues.

**Comment by arturovt** [comment] 2019-08-23 05:19
@Koslun I've pressed Ctrl + F and typed `ngxsstore` and it seems to be there.

**Comment by splincode** [comment] 2019-08-25 19:38
@C1E1S1T https://github.com/ngxs/store/pull/1278

So, Angular 9 works for me, but not sure for lazy modules

**Comment by unlight** [comment] 2019-09-05 08:30
`Angular 9.0.0-next.4`, does not work for lazy modules.

**Comment by arturovt** [comment] 2019-09-05 08:33
@unlight Could you provide a reproduction repo or some screenshots? Would be great.

**Comment by unlight** [comment] 2019-09-05 09:12
@arturovt 
```
git clone https://github.com/unlight/rd-angular-starter
cd rd-angular-starter
git checkout origin/ngxs-router
npm install
npm run dev
// start http://localhost:4200/
// Can't resolve all parameters for RouterState: (?, ?, ?, ?, ?, ?, ?).
```
![image](https://user-images.githubusercontent.com/301732/64328430-79859e00-cfde-11e9-9723-4bf3fdae1f02.png)

**Comment by unlight** [comment] 2019-09-05 09:15
Looks like for non-lazy it doesn't work too for me

**Comment by arturovt** [comment] 2019-09-05 17:15
I've added a comment in the Angular's repo issue.

**Comment by unlight** [comment] 2019-09-05 20:01
Which repo? I could not find it. Could you provide link to this comment?

**Comment by arturovt** [comment] 2019-09-05 21:03
> Which repo? I could not find it. Could you provide link to this comment?

https://github.com/ngxs/store/issues/1165#issuecomment-514107343

**Comment by jtomek** [comment] 2019-09-15 08:07
It's been fixed by the Angular team.

**Comment by arturovt** [comment] 2019-09-15 12:55
> It's been fixed by the Angular team.

Not yet, we're waiting for the next version and probably NGXS will be compatible only with Angular 9+.

**Comment by jtomek** [comment] 2019-09-15 20:54
I see. I thought fixed it here https://github.com/angular/angular/issues/31791

**Comment by arturovt** [comment] 2019-09-15 21:21
> I see. I thought fixed it here [angular/angular#31791](https://github.com/angular/angular/issues/31791)

We haven't checked yet as the new compiler version hasn't been published. Looking forward to the next version, prolly 9.0.0-next.7. But still we need a stable 9 version release :zap:

**Comment by xmlking** [comment] 2019-09-20 00:44
9.0.0-next.7 released

**Comment by arturovt** [comment] 2019-09-20 04:16
Gentlemen, tested with 9.0.0-next.7 and it works:

![image](https://user-images.githubusercontent.com/7337691/65299024-85449900-db76-11e9-9f9e-c95d75b41997.png)

**Comment by splincode** [comment] 2019-09-24 20:20
Not working with ng9-next7

Here is a toy project to reproduce the ngxs/ivy issue - https://github.com/dubzzz/todolist-front/commit/da34247c65785c43ae25d0f23a1950975ece7426

**Comment by mgechev** [comment] 2019-09-26 18:49
@JoostK looked into this. Angular's DI cannot resolve the parameters of the constructor because `AuthenticationState` is only decorated with `@State`. Decorate it with `@Injectable` and everything should work as expected.

**Comment by unlight** [comment] 2019-09-27 18:44
Failed compilation when switching to target = es5
```
ERROR in ./node_modules/@ngxs/router-plugin/__ivy_ngcc__/fesm5/ngxs-router-plugin.js 650:76-100
"export 'NgxsFeatureModule' (imported as 'ɵngcc1') was not found in '@ngxs/store'
```
But ok for es2015.

**Comment by mgechev** [comment] 2019-09-27 19:03
As a workaround keep the current es2015 target and rely on the downleveling with differential loading that Angular CLI performs once it generates the es2015 bundles.

**Comment by splincode** [comment] 2019-09-28 07:40
@mgechev it is bug Angular CLI?

**Comment by JoostK** [comment] 2019-09-28 11:47
@unlight thanks, that is interesting. I was able to reproduce your issue and found an issue with ngcc's processing of private exports.

Previously (pre-Ivy), the compiler would create a private export for all non-public exports, as doing so allows the non-public exports to be referenced outside of the library using their private export that the compiler created. The Ivy compiler also needs to create imports for things imported from a library, but is unaware of the private exports (they were only considered in the pre-Ivy compiler). To remedy this, ngcc analyzes the program to find all non-public exports that the Ivy compiler may need to create references to, and updates the program and declaration files by adding the necessary exports.

After the declaration files have been adjusted during the first run of ngcc, say ES2015, and then the library's ES5 bundle is processed, ngcc will look at the declaration files to determine which exports it needs to add. Since the declaration files have already been updated when running ES2015, it will incorrectly omit the insertion of the private exports to the ES5 bundle. This is where the `export 'NgxsFeatureModule' (imported as 'ɵngcc1') was not found in '@ngxs/store'` error comes from.

I was able to workaround this issue when only the ES5 bundle was processed, but this is an issue that needs to be resolved in ngcc itself.

**Comment by JoostK** [comment] 2019-09-29 21:28
Here's a PR that should fix the `export 'NgxsFeatureModule' (imported as 'ɵngcc1') was not found in '@ngxs/store'` issue: https://github.com/angular/angular/pull/32902

**Comment by paulstelzer** [comment] 2019-11-05 20:25
I can confirm by adding @Injectable() before @State(...) it's working with angular rc0

**Comment by Newbie012** [comment] 2019-11-17 15:48
Error occurs on version `9.0.0-rc.2`:

```
Error: Can't resolve all parameters for AuthState: (?)
...
AuthState --> constructor(public store: Store)
```

**Comment by splincode** [comment] 2019-12-10 20:57
@Newbie012 try last `Angular 9-rc.5` + `ngxs/store@dev`

**Comment by splincode** [comment] 2019-12-10 21:08
But we have problem with integration test

![image](https://user-images.githubusercontent.com/12021443/70569105-51dc3e00-1baa-11ea-9a65-3a3352828b24.png)

**Comment by mgechev** [comment] 2019-12-10 21:45
@splincode can you provide a minimal demo where we can reproduce the problem?

**Comment by splincode** [comment] 2019-12-10 21:56
@mgechev https://github.com/angular/angular/issues/34191

**Comment by splincode** [comment] 2019-12-21 17:46
Worked with Angular 9-rc.7

**Closed by splincode** 2019-12-21 17:46 UTC
Labels: angular:ivy, investigate, not an issue, on hold

**Comment by freemanlam** [comment] 2020-01-13 09:27
Hi all! I'm not sure that is the same problem or just my stupid mistake. I have the problem when try to use di in state like I use it before.

```Error: Can't resolve all parameters for TestState: (?).```

This repo can reproduce the issue, only thing I did after `ng new`, is add `@ngxs/store@dev` and change files inside /src/app.
https://github.com/freemanlam/ng9-ngxs-di-issue

**Comment by splincode** [comment] 2020-01-13 09:37
https://www.ngxs.io/advanced/ivy-migration-guide

https://github.com/freemanlam/ng9-ngxs-di-issue/blob/master/src/app/test.state.ts

Works

```ts
@State<TestStateModel>({
  name: 'test',
  defaults: {
    oh: '123'
  }
})
@Injectable()
export class TestState {

  constructor(
    private testService: testService
  ) {
    debugger;
    testService.test();
  }

}
```

**Comment by freemanlam** [comment] 2020-01-13 10:08
> https://www.ngxs.io/advanced/ivy-migration-guide
> 
> https://github.com/freemanlam/ng9-ngxs-di-issue/blob/master/src/app/test.state.ts
> 
> Works
> 
> ```ts
> @State<TestStateModel>({
>   name: 'test',
>   defaults: {
>     oh: '123'
>   }
> })
> @Injectable()
> export class TestState {
> 
>   constructor(
>     private testService: testService
>   ) {
>     debugger;
>     testService.test();
>   }
> 
> }
> ```

Awesome, I really forgot this change in ng9, thanks :P
