### ISSUE TITLE
🚀[FEATURE]: Support for Angular v13

### ISSUE THREAD

**Issue by kristofdc** [ngxs/store#1803] opened 2021-11-22 19:54 UTC
### Description
Any idea when the Angular 13 support will be available?

I already added release 3.7.2 (may 2021) in our project (https://github.com/ngxs/store/releases), but is not compatible with Angular v13 (also devtools/logging plugin is not yet compatible)

npm ERR! While resolving: alfa-solutions@0.0.0
npm ERR! Found: @angular/core@13.0.0
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=6.1.0 <13.0.0" from @ngxs/store@3.7.2
npm ERR! node_modules/@ngxs/store
npm ERR!   @ngxs/store@"3.7.2" from the root project

**Comment by splincode** [comment] 2021-11-22 20:12
@kristofdc hello, try install beta version
https://www.npmjs.com/package/@ngxs/store/v/3.7.2-dev.master-9a7c431

**Comment by kristofdc** [comment] 2021-11-23 06:34
Thanks @splincode, when can we expect the stable release?

**Comment by splincode** [comment] 2021-11-23 07:25
@markwhitfeld fyi

**Comment by markwhitfeld** [comment] 2021-11-23 08:25
This is a duplicate of #1797. I will close this and reopen the other (which was auto closed by a PR).

**Closed by markwhitfeld** 2021-11-23 08:25 UTC
