### ISSUE TITLE
❓[SUPPORT]: removeItem repairType object possibly undefined

### ISSUE THREAD

**Issue by developer239** [ngxs/store#1715] opened 2021-01-08 14:37 UTC
When I use `removeItem` state operator then TypeScript complains that `message` object can be possibly undefined even though I specified the type for `removeItem` operator. I could fix the issue with optional chaining but that is not possible if I want to use a utility library like `Ramda`

![image](https://user-images.githubusercontent.com/14946081/104027016-135aed80-51c7-11eb-9316-9b3dbf5b79bf.png)

With `Ramda`:

![image](https://user-images.githubusercontent.com/14946081/104027220-5917b600-51c7-11eb-9629-5f07a6ba7f73.png)

How do people use state operators? Do they really use optional chaining EVERY time they use state operator? 🙂

**Comment by developer239** [comment] 2021-01-08 14:42
Offtopic: I wanted to create a bug report but threatening with closing my issue immediately because I don't have a reproduction is kind of off-putting. I understand that you are busy but think about how many people will not report a (potentially major) bug just because they are too lazy creating a reproduction.

**Comment by developer239** [comment] 2021-01-08 16:14
After looking at the codebase I would summarize the problem like this:

When I am using `removeItem` I want it to do two things:
- **find a relevant item that matches my selectors**
- **remove relevant item**

Making the `value` in `Predicate` type optional forces me to do a third thing:
- **consider what to do with items that are not defined if there are gaps in the array**

I don't think that selector should be responsible for the third step.

```
// packages/store/operators/src/remove-item.ts

export function removeItem<T>(
  selector: number | Predicate<T>
): StateOperator<RepairType<T>[]> { // **existing is NEVER undefined**
  return function removeItemOperator(existing: Readonly<RepairType<T>[]>): RepairType<T>[] {
    let index = -1;

    if (isPredicate(selector)) {
      // **selector might fail here in some cases if there are gaps in the array but we could filter the array before using the selector.** Selector should receive only items that it was designed to select from (in this case `T`)
      index = existing.findIndex(selector);
    } else if (isNumber(selector)) {
      index = selector;
    }

    if (invalidIndex(index)) {
      return existing as RepairType<T>[];
    }

    const clone = existing.slice();
    clone.splice(index, 1);
    return clone;
  };
}
```

I can create PR with a fix but I am not sure how would that affect the rest of the codebase but I am pretty sure that this will be too big of a breaking change to go through. I decided to create my own selectors instead.

**Comment by markwhitfeld** [comment] 2023-03-29 14:23
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes some additional types exposed for building operators.
We are closing this issue, because the improvements may assist you in resolving this issue.
Please re-open it if the issue is not resolved.

Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:23 UTC
Labels: investigate, good first issue, discussion, not an issue, released
