### ISSUE TITLE
🚀[FEATURE]: Allow having state action handlers separated into different classes 

### ISSUE THREAD

**Issue by d3v0ps** [ngxs/store#1790] opened 2021-10-01 11:16 UTC
### Relevant Package

 This feature request is for @ngxs/store

### Description
 As our application states grows in terms of actions available for the same State, I would like to be able to define the Action handlers in different files.

### Describe the problem you are trying to solve
 Reduce the State file size by splitting it into multiple files

### Describe the solution you'd like
 Allow multiple State decorators with the same name **or** a new decorator (e.g. StateActionHandler) where we could register action handlers for an already defined State. Another solution would be to add the posibility to specify an State in the Action decorator so we can use the decorator in any injectable service

### Describe alternatives you've considered
 Tried providing different State classes with the same state name but application crashes. Using the Action decorator alone without the State decorator doesn't work too.

**Comment by markwhitfeld** [comment] 2021-10-01 13:24
Have you tried this NGXS Labs plugin from @duffleit?
https://github.com/ngxs-labs/attach-action
It should help you achieve what you are looking for.

Just an aside comment, if your state is getting too large then you should look at breaking it up into smaller states. I spoke to @Carniatto about this 2 years ago and it revolutionised his applications design. I'm sure he'll have something to add on this here, or you can reach out on our NGXS slack channel. I like to aim for states that are quite small and singular responsibility.

Also I would recommend looking into [State Operators](https://www.ngxs.io/advanced/operators) for reusing logic for setting or updating state, as well as leveraging selectors to move your selector logic out of the state ( see [Meta Selectors](https://www.ngxs.io/concepts/select#meta-selectors) - which I like to call queries ). Have a read here too while I'm throwing link spam at you :wink: : https://www.ngxs.io/advanced/optimizing-selectors

**Comment by d3v0ps** [comment] 2021-10-01 13:35
Thank you @markwhitfeld ! I'll check it out. I don't have really big states, but when you have like 5 actions, with calls to services and setStates with patchState operators inside the handlers, the file starts looking a little bit big to me. I want to keep my logic as much isolated as possible, and to me, for example, setActive and fetchData actions in a CRUD style State don't need to be in the same file as they don't relate to each others they just have a dependency in common (the store/state). I was thinking about trying to apply it in similar way than DDD does (single files for each command/action and query/selector handlers)

**Comment by gtteamamxx** [comment] 2021-11-17 13:08
Separaing action handlers will be very helpfull.
My use case is following:

I have special Services provided in `providers` of @Component directive.
I want to provide my ActionHandler and handle it when some action will be dispatched and inject in constructor my special services from `providers` in @Component.

All is fine, I can do this in constructor:

```
    this.myActionSubscription = this.actions$
      .pipe(ofActionDispatched(MyState.myAction))
      .subscribe(this.handleMyAction.bind(this));

```

I can inject my special services, but the problem is I can't delay this action by observable, like you can do this in State via @Action() and  `ctx: StateContext<MyStateModel>`

**Comment by arturovt** [comment] 2022-08-08 19:53
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- There has not been much support from other community members
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:

**Closed by arturovt** 2022-08-08 19:53 UTC
