### ISSUE TITLE
🚀[FEATURE]: Signals

### ISSUE THREAD

**Issue by solenopsys** [ngxs/store#2006] opened 2023-05-05 04:51 UTC
### Relevant Package
3.8.0

### Description
Angular 16 have a signals https://angular.io/guide/signals
You are planed use it ?

**Comment by markwhitfeld** [comment] 2023-05-05 08:29
Yes, definitely. We have actually been working closely with the Angular
team in an internal working group to help to define the Signals API and are
discussing our proposal for how we surface signals in NGXS.

**Comment by jtomek** [comment] 2023-05-15 05:29
That's great! 
Are there any updates on Signals in ngxs?

**Comment by vdiaz1130** [comment] 2023-09-21 18:10
Hi. Any updates on Signals in NGXS. Looking forward to trying this out!

**Comment by RyannGalea** [comment] 2024-01-12 05:02
Yes curious about signal integration progress, currently using 17.1 with input signals and it's very nice.

**Comment by yellowclaw** [comment] 2024-03-20 19:50
Hi, any updates with signals? It would be nice also to have a SignalStore.
I appreciate any help you can provide! 💪

**Comment by amusliner** [comment] 2024-05-14 18:42
Hi! Just wondering if there are any updates on the Signals RFC, Thanks!

**Comment by arturovt** [comment] 2024-06-10 16:13
Great news! [v18.0.0](https://github.com/ngxs/store/releases/tag/v18.0.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the https://github.com/ngxs/store/discussions/2173 if you come across any regressions with respect to your issue.

**Closed by arturovt** 2024-06-10 16:13 UTC
