### ISSUE TITLE
🐞[BUG]: Dynamic selector return type issue

### ISSUE THREAD

**Issue by uragun91** [ngxs/store#1698] opened 2020-11-22 20:05 UTC
### Affected Package

 The issue is caused by package @ngxs/store.

### Is this a regression?

 I don't know

### Description

 The return type of dynamic selector seems to be wrong when using createSelector function. Here is my selector code:
<pre><code>
public static agent(agentId: string): Agent {
    return createSelector(
      [AgentsState],
      (state: AgentsStateModel): Agent => {
        return state.agents.find(agent => agent.agentId === agentId);
      }
    );
  }
</code></pre>
Here is my state code:
<pre><code>
interface Agent {
  agentId: string;
  assistantType: string;
  name: string;
  description?: string;
}

interface AgentsStateModel {
  agents: Agent[];
  searchText: string;
}

@State<AgentsStateModel>({
  name: "agents",
  defaults: {
    agents: [
      {
        agentId: "1",
        assistantType: "dispatcher",
        name: "Agent One"
      }
    ],
    searchText: ""
  }
})
</code></pre>

The error disappears when I set the return type of `agent` selector to `any`. So what should be the return type of this method? Maybe I'm doing something wrong so please point me out where is the problem in my code. Thank you.

## 🔬 Minimal Reproduction

 [Stackblitz](https://stackblitz.com/edit/angular-ngxs-createselector-type-repro)

## 🔥 Exception or Error
<pre><code>
Error in src/app/agents.state.ts (40:12)
Type '(agents: Agent[]) => Agent' is missing the following properties from type 'Agent': agentId, assistantType
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 10.2.0
- @ngxs/store version: 3.7.0

Browser:
- [X] Chrome (desktop) version 86.0.4240.193
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.3  
- Platform:  Linux

**Comment by markwhitfeld** [comment] 2020-11-26 20:44
Hi @uragun91 welcome to NGXS!
A selector is a memoised function that will return some data from some part of your state (potentially produced by another selector). So, `createSelector` returns a function for accessing a value, and not the value itself.
The type of function returned by the `createSelector` will be the same as the second argument to the `createSelector` function.
`createSelector` is essentially adding metadata that describes what selectors ngxs should use to fetch the parameters of this function when selecting from the state.

Your method definition should be:
```TS
public static agent(agentId: string): (state: AgentsStateModel) => Agent {
    return createSelector(
      [AgentsState],
      (state: AgentsStateModel): Agent => {
        return state.agents.find(agent => agent.agentId === agentId);
      }
    );
  }
```
But, in practice I typically let it infer the return type like this:
```TS
public static agent(agentId: string) {
    return createSelector(
      [AgentsState],
      (state: AgentsStateModel): Agent => {
        return state.agents.find(agent => agent.agentId === agentId);
      }
    );
  }
```
Hope that this makes sense. I know that it can be a bit of a different concept to get your head around at first.
Closing because this is not a bug.

**Closed by markwhitfeld** 2020-11-26 20:44 UTC

**Comment by uragun91** [comment] 2020-11-26 20:54
Ok, thank you for the clarifications!
