### ISSUE TITLE
storage: undefined if using key option

### ISSUE THREAD

**Issue by ufoscout** [ngxs/store#423] opened 2018-06-06 10:15 UTC
### Versions
```
* ngxs: 3.1.3
* ngxs/storage-plugin: 3.1.3
* @angular/core: 6.0.3
```

### Repro steps
Initialize the storage plugin with a custom key:
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ...
    NgxsModule.forRoot([]),
    NgxsStoragePluginModule.forRoot({
      key: '@@MY_KEY'
    }),
    NgxsLoggerPluginModule.forRoot(),
    ...
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Observed behavior
If the "key" option is passed to the storage plugin, then the value associated with that key in the local storage is undefined. 
On the contrary, if the key is not specified, the default one (i.e. @@STATE) is used and everything works as expected.

### Desired behavior
The custom key is used instead of @@STATE and everything works the same.

**Comment by amcdnl** [comment] 2018-06-12 13:21
Can you make a demo? I've using this quite a bit and haven't had any issues.

**Comment by hxhieu** [comment] 2018-06-14 23:01
I encountered the same issue and here is what it means - the default @@STATE works but not custom key
![image](https://user-images.githubusercontent.com/781299/41442471-7d7a1d28-708b-11e8-980f-3b653d15c1ff.png)

**Comment by vdiaz1130** [comment] 2018-09-07 01:44
Any updates on this? Looking to use this feature upon app initialization.

**Comment by ph1p** [comment] 2018-11-07 15:04
I tried to solve this issue and I think the whole implementation how the key option works is weird.
You can use strings and arrays. If one of these elements matches an property inside your state, it is set. If not it is undefined. I stopped to try things, because of the migration implementation. I'm new to this library and the migration structure also need keys.

I'm also wondered, that the `@@STATE` is hard coded, because there is line:

**storage.plugin.ts**
```
    const isMaster = key === '@@STATE';
```
and I thought, that the setted `key` option is your new "master".

---

**pseudo-state:**
```
{
  state1: {
    count: 1
  },
  state2: {
    count: 2
  }
}
```
**Implementation:**
```
//...
NgxsStoragePluginModule.forRoot({
    key: 'myState' // is set to undefined
})
//...
```

**Implementation 2:**
```
//...
NgxsStoragePluginModule.forRoot({
    key: 'state1' // is set { count: 1 }
})
//...
```

**Implementation 3:**
```
//...
NgxsStoragePluginModule.forRoot({
    key: ['myState'] // saves nothing
})
//...
```

**Implementation 4:**
```
//...
NgxsStoragePluginModule.forRoot({
    key: ['myState', 'state1'] // saves value of state1 to key "state1" and set "myState" to undefined
})
//...
```

**Comment by camillematters** [comment] 2019-04-16 12:47
Any update on that ? I am facing the same issue : 
My need is to change the key user for the local storage (from @@STATE to app_state), but when I use 

`NgxsStoragePluginModule.forRoot({ key: 'app_state' }),`

then the key app_state in my local storage is undefined, and of course the key @@STATE doesn't exist anymore.

**Comment by camillematters** [comment] 2019-04-16 13:23
Here is a slackblitz to reproduce :
 https://stackblitz.com/edit/angular-hmubmi?file=src%2Fapp%2Fapp.module.ts

You can see in the localstorage that app_state is undefined.
If you remove the key for the storage in the file app.module.ts, then the @@STATE is defined and full.

**Comment by thinkingmedia** [comment] 2019-04-18 16:14
Key is actually the "read" path into the storage object for values to be persisted to localStorage.

With the except of `@@STATE` which tells the plugin to store **all** of the state object.

> My need is to change the key user for the local storage (from @@STATE to app_state), but when I use

You must have a property in your state model named `app_state`.

```
interface Example { app_state: string };

@State<Example>({
     name: "app",
     defaults: { app_state: "Hello World" }
) //......
```

The above will store `app_state: "Hello World"` in localStorage if you set the key option to "app_state".

**Comment by arturovt** [comment] 2019-08-11 16:42
@ufoscout should it be closed? The above answer of the `thinkingmedia` is correct: 

> Key is actually the "read" path into the storage object for values to be persisted to localStorage.

**Comment by ufoscout** [comment] 2019-08-12 11:14
@arturovt 
Honestly, I find the behaviour quite weird and confusing; anyway, if this is the intended behaviour, then this issue should be closed.
Please be sure that this is properly documented anyway.

**Comment by arturovt** [comment] 2019-08-12 11:23
@ufoscout OK, I will made a PR to enhance docs

**Comment by markwhitfeld** [comment] 2019-08-29 12:55
Docs PR has been merged. Closing this issue.

**Closed by markwhitfeld** 2019-08-29 12:55 UTC
Labels: domain:plugins, ready to release
