### ISSUE TITLE
🐞[BUG]: order of actions in redux devtools

### ISSUE THREAD

**Issue by pliersch** [ngxs/store#1922] opened 2022-10-07 19:39 UTC
### Affected Package
The issue is caused by package @ngxs/3.7.5 an before

### Description
The order of actions is wrong in Redux DevTools (Chrome)
The order should be: Load -> Success/Fail not Success/Fail -> Load

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/ngxs-repro-ng11-rxqyxz?file=src%2Fapp%2Fapp.state.ts

## Environment
Libs:
- @angular/core version: 14.2.4
- @ngxs/store version: 3.7.5

Browser:
- Chrome (desktop) version 105/106

**Comment by markwhitfeld** [comment] 2022-12-14 19:22
Closing this as a duplicate of issue #139.
This comment provides more explanation of the behavior: https://github.com/ngxs/store/issues/139#issuecomment-707092714

**Closed by markwhitfeld** 2022-12-14 19:22 UTC
Labels: duplicate
