### ISSUE TITLE
Unordered actions

### ISSUE THREAD

**Issue by mailok** [ngxs/store#327] opened 2018-04-24 18:41 UTC
### Versions

```
* ngxs: 3.0.0-rc.1
* @angular/core: 5.2.10
```

### Repro steps

* Define two actions and my state:

```

@State<SharedModel>({
    name: 'shared',
    defaults: {
        auth: { account: null },
    }
})

export class Login {
    static readonly type = '[Shared] LogIn';
    constructor(public payload: Credentials) {}
}

export class LogInSuccess {
    static readonly type = '[Shared] Login success';
    constructor(public payload: Account) {}
}
```
* my logic:

```
@Action(Login)
    login({ dispatch }: StateContext<SharedModel>, { payload }: Login) {
        return this.authOauth2Service
            .login(Endpoints.LOGIN, payload)
            .switchMap(() => {
                return this.accountService.get(Endpoints.ACCOUNT);
            })
            .pipe(tap(account => dispatch(new LogInSuccess(account))));
    }


@Action(LogInSuccess)
    logInSuccess({ setState, getState }: StateContext<SharedModel>, { payload }: LogInSuccess) {
        setState({
            ...getState(),
            auth: { account: payload }
        });
    }

```

* Dispacht action:

```
this.store.dispatch(new Login(credentials));
```

### Observed behavior

It works well, but it shows me the wrong order in devtools:

![captura](https://user-images.githubusercontent.com/3769277/39207248-81f18d82-47cd-11e8-850c-d581f1f7adf3.PNG)

**Comment by deebloo** [comment] 2018-04-25 14:03
yeah @amcdnl can probably speak better to the root of the problem

**Comment by amcdnl** [comment] 2018-04-26 16:41
I think @markwhitfeld actually fixes this in his PR.

**Comment by mailok** [comment] 2018-05-02 20:12
@amcdnl  Not right now because  I removed the logic to consume services in the state. now only use @ngxs for handling state, do not consume services. It's an approach I'm taking in my application

**Comment by amcdnl** [comment] 2018-05-08 13:17
I believe this should be handled in 3.0, closing for now.

**Closed by amcdnl** 2018-05-08 13:17 UTC
Labels: investigate

**Comment by tpsb** [comment] 2018-06-29 19:49
This should be reopened as the issue is still occuring with version 3.1.4 - see [this sample](https://stackblitz.com/edit/angular-xhfbh1).

**Comment by markwhitfeld** [comment] 2018-06-29 20:21
This is being tracked by an open issue #139.
Read this comment for context on why you are seeing this: https://github.com/ngxs/store/issues/139#issuecomment-390673126
Read the subsequent comments for context  on what we are doing about this.
