### ISSUE TITLE
🐞[BUG]: it seems that Ngxs is not compatible with Jest ESM

### ISSUE THREAD

**Issue by vojtesaak** [ngxs/store#2061] opened 2023-09-25 06:44 UTC
### Affected Package
@ngxs/store

### Description

Tests run fine without ESM. If ESM is enabled, it ends up with error at the file with the NGXS import - it fails when requiring angular.

```
  ● Test suite failed to run

    Must use import to load ES Module: /Users/vojtesaak/imt/ngxs-esm/node_modules/@angular/core/fesm2022/core.mjs

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:850:21)
      at node_modules/@ngxs/store/bundles/ngxs-store.umd.js:2:85
      at Object.<anonymous> (node_modules/@ngxs/store/bundles/ngxs-store.umd.js:5:3)
          at async Promise.all (index 1)
```

## 🔬 Minimal Reproduction

https://github.com/vojtesaak/ngxs-esm

- `npm run test` - without error
- `npm run test-esm` - error

**Comment by jase88** [comment] 2023-12-09 19:19
Same error if using `vitest` with ngxs. Followed the setup here: https://dev.to/brandontroberts/faster-testing-with-angular-and-vitest-274n

So it seems to be ESM related

**Comment by hunter-isaiah96** [comment] 2024-01-07 01:33
Still running into this error, does anyone have a fix?

node_modules/@ngxs/store/bundles/ngxs-store.umd.js:2:83
 ❯ Object.<anonymous> node_modules/@ngxs/store/bundles/ngxs-store.umd.js:5:3

**Comment by theUgluk** [comment] 2024-05-07 20:23
I am still running into this, is this something that's known? Is there a workaround?

**Comment by arturovt** [comment] 2024-06-10 16:14
Great news! [v18.0.0](https://github.com/ngxs/store/releases/tag/v18.0.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the https://github.com/ngxs/store/discussions/2173 if you come across any regressions with respect to your issue.

**Closed by arturovt** 2024-06-10 16:14 UTC
