### ISSUE TITLE
The state created with undefined initial state even when defaults are specified

### ISSUE THREAD

**Issue by catchshyam** [ngxs/store#902] opened 2019-03-07 08:27 UTC
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
The feature state object is created with initial state as undefined (even when the defaults is provided). 

## Expected behavior
The feature state object must use the values given in defaults object definition as initial state.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/ngxs-no-initial-state

Launch the application and click on the hyperlink in home page. Then on the console, you will see the debug message with initial state object.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.5
- @ngxs/store version: 3.4.1
- @ngxs-labs/emitter: 1.9.0
- @ngxs-labs/immer-adapter: 1.1.2

**Comment by splincode** [comment] 2019-03-07 09:09
@markwhitfeld very strange

![image](https://user-images.githubusercontent.com/12021443/53945065-cf31ca00-40d1-11e9-916c-332b3e6a6187.png)

![image](https://user-images.githubusercontent.com/12021443/53945078-d527ab00-40d1-11e9-9e9a-86fdd3661060.png)

**Comment by splincode** [comment] 2019-03-07 09:10
@arturovt problem with emitter plugin?

**Comment by kuhnroyal** [comment] 2019-03-07 09:45
I can confirm this happening with 3.4.0/3.4.1

**Comment by markwhitfeld** [comment] 2019-03-07 10:00
This only affects Emitter plugin users. This is because of the way that Emitter inherits from Store to create an `EmitStore`.
I have found the point at which the state is reset. See this stackblitz:
https://stackblitz.com/edit/ngxs-no-initial-state-debug

This bug is caused by this change in PR #791 
https://github.com/ngxs/store/pull/791/files#diff-084c7b85b6562e3126b58451d5f8943aR20

Ngxs does not expect anyone to inherit from `Store` and essentially run this code twice. Emitter does some things with Ngxs internals that are not usual plugin behaviours.

**Comment by splincode** [comment] 2019-03-07 14:15
fixed 3.4.2

**Comment by xmlking** [comment] 2019-03-15 00:04
when we have `default` state and partial state coming from ` NgxsStoragePluginModule`
default state is still coming as undefined

Store
https://github.com/xmlking/ngx-starter-kit/blob/develop/libs/auth/src/lib/auth.state.ts#L31
NgxsStoragePluginModule
https://github.com/xmlking/ngx-starter-kit/blob/develop/libs/core/src/lib/core.module.ts#L66

![image](https://user-images.githubusercontent.com/627951/54399241-bea5c480-467a-11e9-8e51-5308571397b5.png)

if I remove my data from LocalStorage and reload page then  i see `Auth Mode Changed: undefined => ImplicitFLow`  

![image](https://user-images.githubusercontent.com/627951/54399310-04fb2380-467b-11e9-94c4-6efd2f56d299.png)

**Comment by splincode** [comment] 2019-03-15 07:29
@markwhitfeld

**Comment by synec** [comment] 2019-03-24 14:24
I facing the same issue as @xmlking 
When state defaults are defined and the keys get stored via `NgxsStoragePluginModule` the defaults are not loaded.

**Comment by splincode** [comment] 2019-05-18 06:29
@xmlking Please try new version! 

```
npm install @ngxs/store@dev
```

**Comment by splincode** [comment] 2019-07-23 10:00
Released in 3.5.0

**Closed by splincode** 2019-07-23 10:00 UTC
Labels: bug/regression, ready to release

**Comment by cihataykas** [comment] 2023-08-01 15:30
@splincode the issue is still reproducible in `3.7.3`
