### ISSUE TITLE
WebSocket stream is killed after a WebSocketDisconnected action completes

### ISSUE THREAD

**Issue by estelle0500** [ngxs/store#977] opened 2019-04-05 08:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Trying to use the WebSocket plugin to connect with my server.
Once a `WebSocketDisconnected` action happens, the `WebSocketSubject` produces an error. Even if I try to reconnect by dispatching a `ConnectWebSocket` action afterwards, no more data comes through the subscription to `WebSocketSubject` as the stream has been killed.

## Expected behavior

After reconnecting, the `WebSocketSubject` should continue to emit data sent from the server.

## What is the motivation / use case for changing the behavior?

The connection with the server may not be stable and I don't want to force the user to refresh the page (which would regenerate everything, including creating a new `WebSocketSubject`) to be able to see the new changes.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.11
- @ngxs/store version: 3.4.1
- @ngxs/websocket-plugin version: 3.4.1

Browser:
- [ X ] Chrome (desktop) version 73.0.3683.86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
Others:

</code></pre>

**Comment by markwhitfeld** [comment] 2019-04-06 05:36
Looking at the code in the websocket plugin this definitely seems to be an issue.
@ngxs/core As part of fixing this we need to get the websocket tests working, reproduce the error and fix it.

**Comment by arturovt** [comment] 2019-05-25 17:49
@estelle0500 

I've published a PR that fixes that issue. Would you like to help me with your regression feedback if everything is ok or not? So we're able to add that fix to the `3.5.0` release.

P.S. I will notice you when this PR gets merged

**Comment by arturovt** [comment] 2019-05-25 20:49
@estelle0500 

The PR was merged. You can try it out by running:
```console
yarn upgrade @ngxs/websocket-plugin@dev
```

The latest `dev` version is `3.4.3-dev.master-dad8ead`

**Comment by splincode** [comment] 2019-07-23 10:01
Released in 3.5.0

**Closed by splincode** 2019-07-23 10:01 UTC
Labels: domain:plugins, ready to release
