### ISSUE TITLE
🐞[BUG]: You've forgotten to import "NgxsSelectSnapshotModule" // the NGXS module

### ISSUE THREAD

**Issue by elegon32** [ngxs/store#1723] opened 2021-02-27 18:33 UTC
### Description
We see in our server logs many of these 2 FATAL Errors on production and on non-production environments:
* FATAL [main.js:xx] NgxsSelectSnapshotModuleIsNotImported [Error]: You've forgotten to import "NgxsSelectSnapshotModule"! at assertDefined (/opt/app/dist/server/main.js:xx:yy) at getStore
* FATAL [main.js:xx] Error: You have forgotten to import the NGXS module! at createSelectObservable (/opt/app/dist/server/main.js:1:yy)

We clearly have imported both ngxs modules in AppModule and in the Feature Modules.
In App module: 
<pre><code>
NgxsModule.forRoot(
      [
      xxx....
      ],
      {
        developmentMode: !environment.production,
      },
    ),
    NgxsRouterPluginModule.forRoot(),
    NgxsFormPluginModule.forRoot(),
    NgxsSelectSnapshotModule.forRoot(),
    NgxsStoragePluginModule.forRoot({
         ...xxx
      },
    }),
    NgxsReduxDevtoolsPluginModule.forRoot({
      name: 'xxxx',
      disabled: environment.production,
    }),
</code></pre>

in Feature Module:
<pre><code>
    NgxsModule.forFeature([xxx, yyy]),
    NgxsSelectSnapshotModule,
</code></pre>

It is a very huge project with many modules and components... And the errors are only happening via SSR, and there it happens rarely on our dev machines... When it does, though, we see a LOT of Error statements successively while no other component or module is complaing with an error. It is just ngxs. 
It seems, that SSR still deliveres the html, and the Angular app loads still well on the client (including all ngxs stuff)

## 🔬 Minimal Reproduction
Ok. We found out how to reproduce:
1. open a page in browser
2. refresh
3. quickly abort loading
4. quickly refresh again
5. --> many many FATAL Errors

Guess: This might be caused by angular destroying all stuff and both ngxs modules will clear the Injector onDestroy.
As the errors happens ONLY when we reload quickly after aborting (just aborting never creates the errors), it must be sth about angular universal still (re-?) using some components while ngxs already got rid of its injector reference.

## 🔥 Exception or Error
<pre><code>
FATAL [main.js:2897] Error: You have forgotten to import the NGXS module! 
at createSelectObservable (/opt/app/dist/server/main.js:1:xx) 
at AppComponent.get [as progress] (/opt/app/dist/server/main.js:1:xx) 
at AppComponent_Template (/opt/app/dist/server/main.js:2897:1625353) 
at executeTemplate (/opt/app/dist/server/main.js:2897:xx) 
at refreshView (/opt/app/dist/server/main.js:2897:xx) 
at refreshComponent (/opt/app/dist/server/main.js:2897:xx) 
at refreshChildComponents (/opt/app/dist/server/main.js:2897:xx) 
at refreshView (/opt/app/dist/server/main.js:2897:xx) 
at renderComponentOrTemplate (/opt/app/dist/server/main.js:2897:xx)
at tickRootContext (/opt/app/dist/server/main.js:2897:xx)

or....

FATAL [main.js:2897] NgxsSelectSnapshotModuleIsNotImported [Error]: You've forgotten to import "NgxsSelectSnapshotModule"! 
at assertDefined (/opt/app/dist/server/main.js:2897:xx) 
at getStore (/opt/app/dist/server/main.js:2897:xx) 
at XXXComponent.get [as isXXX] (/opt/app/dist/server/main.js:2897:xx) 
at XXXComponent_Template (/opt/app/dist/server/main.js:2897:xx) 
at executeTemplate (/opt/app/dist/server/main.js:2897:xx) 
at refreshView (/opt/app/dist/server/main.js:2897:xx) 
at refreshComponent (/opt/app/dist/server/main.js:2897:xx) 
at refreshChildComponents (/opt/app/dist/server/main.js:2897:xx) 
at refreshView (/opt/app/dist/server/main.js:2897:xx) 
at refreshComponent (/opt/app/dist/server/main.js:2897:xx)
</code></pre>

## Environment

<pre><code>
Libs:
    "@angular/core": "^11.0.6",
    "@ngxs/store": "^3.7.1",
    "@ngxs-labs/select-snapshot": "^2.0.1",

Browser: only on SSR
</code></pre>

**Comment by elegon32** [comment] 2021-03-01 08:31
Ok. We found out how to reproduce:
1. open a page in browser
2. refresh
3. quickly abort loading
4. quickly refresh again
5. --> many many FATAL Errors

Guess: This might be caused by angular destroying all stuff and both ngxs modules will clear the Injector onDestroy.
As the errors happens ONLY when we reload quickly after aborting (just aborting never creates the errors), it must be sth about angular universal still (re-?) using some components while ngxs already got rid of its injector reference.

**Comment by asaadedd** [comment] 2021-03-01 15:06
I have forked the repository and managed to reproduce this issue on the example application in the integration folder.
https://github.com/asaadedd/store

The root cause of this issue is this file: https://github.com/ngxs/store/blob/master/packages/store/src/decorators/select/select-factory.ts

The store key that is present in the SelectFactory class is a singleton for the entire server ( it is not an Angular specific singleton ). You can see that from the way it is used inside the decorator: https://github.com/ngxs/store/blob/8b52ae654c0a707612a8d23bde4737e69cbb8ee9/packages/store/src/decorators/select/symbols.ts#L11

I would suggest refactoring this decorator to depend on the Store in every component that is used rather than on the store which is a singleton for the entire server.

Also this issue is present inside the select-snapshot repository as well ( https://github.com/ngxs-labs/select-snapshot )

**Comment by arturovt** [comment] 2021-03-02 09:55
This seems to be a duplicate of #1646 . Could you make a simple reproducible example thus any developer will be able to fork it, debug locally and probably provide a fix for that?

**Comment by asaadedd** [comment] 2021-03-02 11:47
This can be reproduced in my cloned repository: https://github.com/asaadedd/store in the app inside the integration folder. I cannot create a Stackblitz because the error is present in the SSR logs.

Also, you can check my analysis in the comment above.

**Comment by hurrii** [comment] 2021-03-18 08:59
Having the same issue.

**Comment by martinsotirov** [comment] 2021-03-19 10:39
Same problem in my server side rendered app. Ao much so that when we try to run a SEO crawler, it crashes the the express app that's doing the server side rendering.

**Comment by asaadedd** [comment] 2021-03-19 11:04
We are experiencing the same SEO crawler bug as well

**Comment by samizarraa** [comment] 2021-03-22 12:54
Same problem in our server side rendered app

> Libs:
    "@angular/core": "^11.2.6",
    "@nguniversal/express-engine": "^11.2.1",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",

**Comment by elegon32** [comment] 2021-03-22 13:04
So, basically, there should be a **WARNING in the ngxs docs**, that these 3 decorators should not be used, when using (or planed to use) with SSR / Angular Universal: 

- Select
- SelectSnapshot
- ViewSelectSnapshot

**Comment by markwhitfeld** [comment] 2021-03-25 13:37
@arturovt have you had a chance to look into this issue?
Potentially a fix could be if we could access the injector on the local instance then we could access the store that way. This could've possible with Ivy, but I'm not sure. What do you think?

**Comment by asaadedd** [comment] 2021-03-26 05:55
It is possible with ivy, I have done a fix on our branch and use https://www.npmjs.com/package/patch-package to patch our version of NGXS and NGXS-labs. I will try to create a PR with my solution hopefully this weekend. But there are some downside of this:
1. It cannot be used in without ivy ( no support for previous versions of angular )
2. it needs to be properly tested on JIT ( there is some code to cover the JIT compiler but I did not manage to properly tested on JIT )

**Comment by markwhitfeld** [comment] 2021-03-26 09:15
Fantastic! I look forward to seeing your PR.
We are happy to have Ivy specific code and to stipulate that the solution requires Ivy. ViewEngine is scheduled to be removed by Angular v13 as far as I have heard.

**Comment by markwhitfeld** [comment] 2021-04-28 09:29
@elegon32, @asaadedd, @hurrii, @martinsotirov and @samizarraa there is work currently happening to fix this issue.
See PR #1740 for progress. @arturovt is an absolute legend!!!

PS. @asaadedd, you mentioned that you had been looking into a fix, could you have a look at the PR above and give your thoughts?

**Comment by markwhitfeld** [comment] 2021-05-03 09:44
Hi @elegon32, @asaadedd, @hurrii, @martinsotirov and @samizarraa, the PR from @arturovt has been merged into master, so it will be available on NPM through the @ngxs/store@dev version.
This will resolve the issue for only the `@Select` decorator so far. Please could you test it out and confirm that it resolves this issue for you?
`@SelectSnapshot` and `@ViewSelectSnapshot` are still to be resolved (using the same technique).

**Comment by markwhitfeld** [comment] 2021-06-24 07:20
@arturovt could you look into resolving this for @SelectSnapshot and @ViewSelectSnapshot too?

**Comment by FerBastiaens** [comment] 2022-05-11 12:04
Still experiencing this issue and waiting for a fix. Are there any plans for it?

**Comment by Roelensdam** [comment] 2022-05-12 10:41
@markwhitfeld I've just tested the fix in the @ngxs/store@dev version. It looks like it's fixed. Can't reproduce the bug anymore. Great job!

When can we expect the 3.7.3 release with this fix ?

**Comment by roldengarm** [comment] 2022-06-29 18:33
I just ran into the same issue when upgrading to Angular 14 and upgrading from 3.7.3 to 3.7.4. Very frustrating!

**Comment by fpmk** [comment] 2022-07-01 06:54
> I just ran into the same issue when upgrading to Angular 14 and upgrading from 3.7.3 to 3.7.4. Very frustrating!
> 
> I'm NOT using SSR, and it worked fine in Angular 13. It happens when I switch lazy loaded routes, and it seems to fail on a state that is imported in the root state, i.e. available in both.

same for me

**Comment by laurentsd** [comment] 2022-07-04 17:05
same for me :-(

**Comment by arturovt** [comment] 2022-07-04 19:03
We're reverting changes done to the `@Select` decorator. I'll close this issue since it's complicated to track the same issue in multiple places. Also see this comment: https://github.com/ngxs/store/issues/1854#issuecomment-1167955493.

**Closed by arturovt** 2022-07-04 19:03 UTC
Labels: ready to release

**Comment by laurentsd** [comment] 2022-07-06 03:18
@arturovt Thank you. Replace @Select with store.select() solves the problem for me indeed!
