### ISSUE TITLE
🐞[BUG]: Sometimes store is null when a selector is subscribed on constructor

### ISSUE THREAD

**Issue by GaulthierToussaint** [ngxs/store#1897] opened 2022-08-04 11:18 UTC
### Affected Package
@ngxs/store 3.7.4 with Angular 14

### Is this a regression?

Yes, it worked correctly with @ngxs/store 3.6.2 and Angular 13

### Description

On constructor of a component, I subscribe to a selector value and do some stuff. When I firstly navigate to the page of the given component, everything works well, then I navigate to another view and finally I go back to the first view, here an error appears saying that the store is null.

## 🔬 Minimal Reproduction
This code worked well with Angular 13 and @ngxs/store 3.6.2 but do not work with @ngxs/store 3.7.4 and Angular 14.
```typescript 
export class AtUserListComponent {
    public dataSource: AtListDataSource<UserPro> =
        new AtListDataSource<UserPro>();

    @Select(UserState.getUsersState)
    public users$: Observable<UserPro[]>;

    @Select(UserState.getUsersCount)
    public usersCount$: Observable<number>;

    constructor(
        private store: Store,
    ) {
        combineLatest(
            this.users$.pipe(filter((v) => v !== undefined)),
            this.usersCount$.pipe(filter((v) => v !== undefined))
        )
            .subscribe(([payload, totalCount]) => {
                this.dataSource.pages = { totalCount, payload };
                this.dataSource.setLoading(false);
            });
    }
}
```

A workaround we find is to move the subscription into a ngOnInit or ngAfterViewInit and then everything works well.

```typescript 
export class AtUserListComponent {
    ...
    constructor(
        private store: Store,
    ) {
    }

    public ngOnInit() {
        combineLatest(
            this.users$.pipe(filter((v) => v !== undefined)),
            this.usersCount$.pipe(filter((v) => v !== undefined))
        )
            .subscribe(([payload, totalCount]) => {
                this.dataSource.pages = { totalCount, payload };
                this.dataSource.setLoading(false);
            });
    }
}
```

Is there something new in angular 14 that would cause this to stop working? Or it's something about the new version of @ngxs/store?
## 🔥 Exception or Error
<pre><code>
core.mjs:7640 ERROR TypeError: Cannot read properties of null (reading 'select')
    at createSelectObservableIvy (ngxs-store.js:3844:101)
    at createSelectObservable (ngxs-store.js:3800:11)
    at ngxs-store.js:3931:36
    at doInnerSub (mergeInternals.js:19:19)
    at outerNext (mergeInternals.js:14:57)
    at OperatorSubscriber._next (OperatorSubscriber.js:9:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at ReplaySubject._subscribe (ReplaySubject.js:31:24)
    at ReplaySubject._trySubscribe (Observable.js:37:25)
    at ReplaySubject._trySubscribe (Subject.js:71:22)
</code></pre>

This is the code on the ngxs-store.js file where the error occured:
<pre><code>
function createSelectObservableIvy(selector, store) {
    return ngDevMode && !store ? throwSelectFactoryNotConnectedError() : ((store)).select(selector);
}
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 14.1.0
- @ngxs/store version: 3.7.4
</code></pre>

**Comment by arturovt** [comment] 2022-08-04 12:13
Duplicate of #1854.

**Closed by arturovt** 2022-08-04 12:13 UTC
