### ISSUE TITLE
🐞[BUG]: Cannot read properties of undefined (reading 'NGXS_META')

### ISSUE THREAD

**Issue by xamelion** [ngxs/store#2101] opened 2024-02-22 14:45 UTC
Affected Package
The issue is caused by package @ngxs/store.

Is this a regression?
Yes, the previous version in which this bug was not present was: 3.7.1

Description
A clear and concise description of the problem. Getting error "Cannot read properties of undefined" when initializing NgxsFeatureModule with @ngxs/store version 3.8.2 and Angular version 17.0.9 during server-side rendering (SSR) build.

🔥 Exception or Error

Copy code
TypeError: Cannot read properties of undefined (reading 'NGXS_META')
Stack trace:

```
TypeError: Cannot read properties of undefined (reading 'NGXS_META')
    at findName (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2542802)
    at Array.map (<anonymous>)
    at /builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2542944
    at Array.reduce (<anonymous>)
    at buildGraph (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2542838)
    at StateFactory2.add (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2542970)
    at StateFactory2.addAndReturnDefaults (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2544423)
    at new NgxsFeatureModule2 (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2553017)
    at NgxsFeatureModule2.ɵfac [as useFactory] (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:23:2553370)
    at Object.factory (/builds/csgofast-new/frontend/angular/dist/apps/gofast-app/server/main.js:1281:55109)
```

Libs:  

- @angular/core version: 17.0.9
- @ngxs/store version: 3.8.2

Node version: 18
Platform: Linux

Build:

- Angular SSR build

**Comment by arturovt** [comment] 2024-02-23 20:33
Can you provide a minimal reproducible example?

**Comment by arturovt** [comment] 2024-03-12 14:53
Closing since no reproducible example is provided.

**Closed by arturovt** 2024-03-12 14:53 UTC
