### ISSUE TITLE
🐞[BUG]: Router Plugin overrides inner navigation with redirect url

### ISSUE THREAD

**Issue by anschm** [ngxs/store#1898] opened 2022-08-04 12:45 UTC
### Affected Package
This issue is caused by package ngxs/router-plugin.

### Description

In my case we are using auth0 as OIDC management system. If a blocked user would like to login auth0 redirects to the callback url with the following query parameters ?error=unauthorized&error_description=user is blocked and so on. This redirect is handled from the auth0 angular library and can be observed. We are catching this error in our application and would like to navigate to a specific page which shows the user that he is blocked. But this does not work, because the router plugin canceled our inner navigation to triggers a new navigation to the redirect url which was performed from the auth0 server. This is done by the following code:

const subscription = this._router.events
      .pipe(first((event): event is RoutesRecognized => event instanceof RoutesRecognized))
      .subscribe(({ url }) => {
        // `location.pathname` always equals manually entered URL in the address bar
        // e.g. `location.pathname === '/foo'`, but the `router` state has been initialized
        // with another URL (e.g. used in combination with `NgxsStoragePlugin`), thus the
        // `RouterNavigation` action will be dispatched and the user will be redirected to the
        // previously saved URL. We want to prevent such behavior, so we perform this check
        // `url` is a recognized URL by the Angular's router, while `currentUrl` is an actual URL
        // entered in the browser's address bar
        // `PathLocationStrategy.prototype.path()` returns a concatenation of
        // `PlatformLocation.pathname` and normalized `PlatformLocation.search`.
        // `Location.prototype.normalize` strips base href from the URL,
        // if `baseHref` (declared in angular.json) for example is `/en`
        // and the URL is `/test#anchor` - then `_locationStrategy.path(true)` will return `/en/test#anchor`,
        // but `/en/test#anchor` is not known to the Angular's router, so we have to strip `/en`
        // from the URL
        const currentUrl = this._location.normalize(this._locationStrategy.path(true));
        const currentUrlTree = this._urlSerializer.parse(currentUrl);
        // We need to serialize the URL because in that example `/test/?redirect=https://google.com/`
        // Angular will recognize it as `/test?redirect=https:%2F%[2Fwww.google.com](http://2fwww.google.com/)%2F`
        // so we have to run the `currentUrl` via the `UrlSerializer` that will encode characters
        const currentSerializedUrl = this._urlSerializer.serialize(currentUrlTree);
        // If URLs differ from each other - we've got to perform a redirect to the manually entered URL
        // in the address bar, as it must have a priority
        if (currentSerializedUrl !== url) {
          this._router.navigateByUrl(currentUrl);
        }
      });

## 🔬 Minimal Reproduction

I  implemented a minimal reproduction example:

https://stackblitz.com/edit/angular-ivy-4exios?file=src/app/app.module.ts
https://angular-ivy-4exios.stackblitz.io

Perform a login with the following user date:
user: ansch@test.de
pw: test@1234

The Hello-Page is show and this is wrong. Within the auth.state we are navigating to /example/blocked and the Blocked-Page should be shown.

## Environment

Libs:
- @angular/core version: 14.1.0
- @ngxs/store version: 3.7.4

Browser:
- Chrome

For Tooling issues:
- Platform:  Mac, Linux, Windows

**Comment by markwhitfeld** [comment] 2022-08-08 22:27
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:27 UTC
Labels: domain: plugins, priority: medium, type: bug/fix, released
