### ISSUE TITLE
🐞[BUG]: Unexpected value 'NgxsRootModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.

### ISSUE THREAD

**Issue by BorisDutkin** [ngxs/store#1735] opened 2021-04-19 04:19 UTC
### Description

 Nx Workspace lib component testing

## 🔬 Minimal Reproduction

```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { NgxsModule } from '@ngxs/store';

import { SignInComponent } from './sign-in.component';

describe('SignInComponent', () => {
  let component: SignInComponent;
  let fixture: ComponentFixture<SignInComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [SignInComponent],
      imports: [
        RouterTestingModule,
        NgxsModule.forRoot([], { developmentMode: true }),
      ],
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(SignInComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

## 🔥 Exception or Error
 Unexpected value 'NgxsRootModule' imported by the module 'DynamicTestModule'.
Please add an @NgModule annotation.

## Environment

<pre><code>
Libs:
- @angular/core version: ^11.2.0
- @ngxs/store version: ^3.7.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment] 2021-04-28 22:45
Closing as _not reproducible_. Feel free to re-open when the reproducible example is provided.

**Comment by nicodh** [comment] 2021-07-16 06:32
I have the same error with 
- @angular/core version: ^11.2.0
- @ngxs/store version: ^3.7.2
Also running my test in nx workspace.

**Comment by nicodh** [comment] 2021-07-16 12:20
Here is an example https://github.com/nicodh/ngxs-testing

**Comment by jonaskuske** [comment] 2021-11-15 07:24
Happens for me too, on Angular 12.2.3

**Comment by jonaskuske** [comment] 2021-11-15 07:35
Update: in [this issue discussion](https://github.com/ng-packagr/ng-packagr/issues/355) it was mentioned that the problem might come from faulty or missing metadata by the Angular compiler. So I ran **`npx ngcc`** again and that fixed the issue for me!

**Comment by Quraian** [comment] 2021-12-07 13:35
Me too! I'm on Angular 13, ```npx ngcc``` seems to resolves the issue.

**Comment by irowbin** [comment] 2021-12-16 09:27
I am also still having this issue even when the angular v13 compatible version of store `3.7.3` is installed. 😕

**Comment by splincode** [comment] 2021-12-16 09:29
@irowbin please, provide your reproduction on github

**Comment by yadue** [comment] 2022-01-11 08:54
@splincode from what I see _isAngularInTestMode currently checks for MockNgModuleResolver but ResourceProvider is being provided.

https://i.imgur.com/SxvhP2t.png

**Comment by splincode** [comment] 2022-01-11 09:41
@yadue hello, could you send PR with fix current bug, please?

**Comment by yadue** [comment] 2022-01-11 12:37
there is a lot to be done since it's not backward compatible, I don't think I will have enough time for this, especially ngxs dependencies are set to version 9 atm.

**Comment by splincode** [comment] 2022-01-11 13:00
@markwhitfeld can we drop support angular 9, 8, 7, 6?

**Comment by adnanebrahimi** [comment] 2022-02-27 10:20
I have same issue after Upgrading NX and Angular and NGXS to latest versions

**Comment by fergardi** [comment] 2022-04-01 06:35
I have this error as well upgrading to latest versions.

**Comment by irowbin** [comment] 2022-06-10 02:44
Are we planning to fix this? Angular has released v14 already and this issue is a blocker. 🙂

**Closed** 2022-06-15 21:29 UTC

**Comment by teebodscvr** [comment] 2022-10-19 13:43
> Me too! I'm on Angular 13, `npx ngcc` seems to resolves the issue.



> Update: in [this issue discussion](https://github.com/ng-packagr/ng-packagr/issues/355) it was mentioned that the problem might come from faulty or missing metadata by the Angular compiler. So I ran **`npx ngcc`** again and that fixed the issue for me!

Hi, thanks a lot. This fixed my issue too. But why did this work?
I am on Angular and Nx version 14, Jest and @ngxs/store@3.7.5
