### ISSUE TITLE
🚀[FEATURE]: Give back control about NgxsConfig.developmentMode 

### ISSUE THREAD

**Issue by maku** [ngxs/store#1875] opened 2022-07-10 12:30 UTC
### Relevant Package

This feature request is for @ngxs/store

### Description
Currently (since version 3.7.4) it seems that the developmentMode parameter in NgxsConfig has no effect as long the Ivy compiler is used.  This effects how object freezing is handled. Objects are freezed when dev mode is active without the possibility to overrule this.

e.g. The point is that my app works with angular version 14.0.5 and @ngxs version 3.7.3 but not with version 3.7.4

### Describe the problem you are trying to solve
This breaks existing code without the possibility to set the behaviour via a config flag (because objects are freezed by ngxs based on environment)

### Describe the solution you'd like
Give back the behaviour to set the developmentMode from the outside to handle object freezing.

**Comment by evkw** [comment] 2022-07-12 04:32
I have the same issue. Seems to also be causing issues with internal NGXS things as well 
![image](https://user-images.githubusercontent.com/15670238/178409019-87332cf6-1533-45e7-8da1-35a72aac698c.png)

**Comment by arturovt** [comment] 2022-07-15 11:14
@evkw that's not related.

@maku we want to tree-shake `deepFreeze` in production mode since it's recommended to be used only in development to ensure you're not doing state mutations. The `deepFreeze` is used when the development mode is enabled and it seems weird if you keep development mode enabled in production.

**Comment by evkw** [comment] 2022-07-15 11:36
@arturovt the stack trace goes into deepFreeze and is resolved when reverting to an earlier version of ngxs.

We have an app that's been in production for a few years now with the flag set to true. I get it's best practice to deepFreeze in dev and if errors surfaced at compile time it would be an easy pill to swallow, but the app I work on has a few hundred lazy loaded feature states that now might be a time bomb because I can't guarantee every line of code in a feature state is hit with e2e. This change basically locks us at 3.7.3. 

Terser probably works fine but it's another layer of complexity where a configuration was fine before.

I also understand it puts us at risk of future Dev in NGXS causing issues with mutated state.. but being stuck at 3.7.3 is probably more of a risk.

**Comment by maku** [comment] 2022-07-15 11:49
> @evkw that's not related.
> 
> @maku we want to tree-shake `deepFreeze` in production mode since it's recommended to be used only in development to ensure you're not doing state mutations. The `deepFreeze` is used when the development mode is enabled and it seems weird if you keep development mode enabled in production.
> 
> What I can propose is that we provide a variable called `ngxsForceFreeze` that you can explicitly provide through Terser and it will always freeze objects based on your Terser configuration.

As I wrote, all we need is to turn off "deepFreeze" in development mode to have the same behaviour like in version 3.7.3. And we are not using development mode in production…

**Comment by evkw** [comment] 2022-07-15 11:50
@maku he means using production mode in Dev, but I share your frustration

**Comment by arturovt** [comment] 2022-07-15 12:12
@evkw I understand your stack trace but it's not related to this issue. It's related to this one #1854.

**Comment by evkw** [comment] 2022-07-15 12:13
> @evkw I understand your stack trace but it's not related to this issue. It's related to this one #1854.

It's not relevant to this thread, I shouldn't have mentioned it

**Comment by arturovt** [comment] 2022-07-15 12:20
I need to rework the `if-else` conditions to respect both `ngDevMode` and `developmentMode` options.

**Comment by markwhitfeld** [comment] 2022-08-08 22:24
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:24 UTC
Labels: domain: core, type: bug/fix, released
