### ISSUE TITLE
🐞[BUG]: Latest Angular release has removed eivyEnabled

### ISSUE THREAD

**Issue by BillClyde** [ngxs/store#1974] opened 2023-03-08 21:17 UTC
### Affected Package
This is affecting the Store

### Is this a regression?
This is being caused by a change in the Angular library

### Description

Building an Angular project fails with an error "eivyEnabled not found in '@angular/core'

## 🔬 Minimal Reproduction

This is not a code issue, it is a library incompatibility issue. The latest build of Angular breaks ngxs/store 

## 🔥 Exception or Error
<pre><code>
./node_modules/@ngxs/store/__ivy_ngcc__/fesm2015/ngxs-store.js:2566:6-17 - Error: export 'ɵivyEnabled' (imported as 'ɵivyEnabled') was not found in '@angular/core'

</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 15.2.2
- @ngxs/store version: 3.7.5

Browser:
N/A
 
For Tooling issues:
- Node version: 14
- Platform:  Windows

**Comment by markwhitfeld** [comment] 2023-03-08 21:54
Thank you for reporting the issue. As far as we were aware, this was not supposed to be dropped until Angular 16.
We were holding off the release due to a [TypeScript bug](https://github.com/microsoft/TypeScript/issues/52004), but it seems that now we can't wait any longer.

This comment gives a better explanation of the TS issue: https://github.com/ngxs/store/issues/1818#issuecomment-1440784120

**Comment by smarza** [comment] 2023-03-08 23:09
Same issue here.

**Comment by oyesiji** [comment] 2023-03-09 15:22
> PS. This is fixed in master. For now, you can use the `@dev` version of NGXS. This is a release candidate of the next minor release. It will be released in the next week or so.
Please  how do i reference the dev version in my package.json?

**Comment by oyesiji** [comment] 2023-03-09 15:49
> > PS. This is fixed in master. For now, you can use the `@dev` version of NGXS. This is a release candidate of the next minor release. It will be released in the next week or so.
> > **Please  how do i reference the dev version in my package.json?**

Am Good thank you

**Comment by datpt154** [comment] 2023-03-13 04:19
![Screenshot 2023-03-13 at 11 19 06](https://user-images.githubusercontent.com/4745820/224607290-f5171d0d-8ed5-4595-8061-d466b03d6580.png)

I tried to use @dev version of NGXS, but the same error still occurred, can you guys please re-check it again? Thank

**Comment by oyesiji** [comment] 2023-03-13 11:56
> ![Screenshot 2023-03-13 at 11 19 06](https://user-images.githubusercontent.com/4745820/224607290-f5171d0d-8ed5-4595-8061-d466b03d6580.png)
> 
> I tried to use @dev version of NGXS, but the same error still occurred, can you guys please re-check it again? Thank

It worked for me

**Comment by internalsystemerror** [comment] 2023-03-13 13:06
A new dev package hasn't been released for months, I assume you would need to remove the current ngxs packages and add this monorepo as a github package to npm.

**Comment by ElecTreeFrying** [comment] 2023-03-14 07:52
Any updates on this issue? When is the `@dev` going to be merged?

**Comment by miguelromeroh** [comment] 2023-03-14 23:11
For now you can install the release candidate this way

``` npm i @ngxs/store@dev ```

**Comment by alybal** [comment] 2023-03-15 10:34
Any update when the next minor release?

**Comment by abhi5movva** [comment] 2023-03-16 17:22
Any update when the next minor release?

**Comment by abhi5movva** [comment] 2023-03-16 17:26
For every build, do we need to install ngxs/store ? by using this command npm i @ngxs/store@dev. Even though it is installed i am getting error after build. It is getting resolved after installing again.

**Comment by chabb** [comment] 2023-03-20 12:31
Hello ! This issue is breaking the build in some of our projects, it would be good to have a version that works with angular 15.2.2. This will needed anyway for angular 16

**Comment by datpt154** [comment] 2023-03-22 01:57
> For every build, do we need to install ngxs/store ? by using this command npm i @ngxs/store@dev. Even though it is installed i am getting error after build. It is getting resolved after installing again.

same to me ^.^

**Comment by ElecTreeFrying** [comment] 2023-03-23 06:06
> PS. This is fixed in master. For now, you can use the `@dev` version of NGXS. This is a release candidate of the next minor release. It will be released in the next week or so.

Hi, thanks for the update on the NGXS issue. Can you please let us know when the next minor release will be officially released this week? We appreciate your efforts in fixing this issue and are looking forward to the upcoming release. Thanks.

**Comment by developer239** [comment] 2023-03-26 19:12
I would like to start by saying that I absolutely love NGXS and what you guys created but ...

... I came back to Angular to refresh my pet project and see what changed in the last three years and from what I remember IVY happened in version 9. The fact that you weren't able to update to Ivy in 3+ years is ... not ideal to say the least.

**Comment by internalsystemerror** [comment] 2023-03-27 12:32
To all those asking "when fly", pls be patient. Remember we're benefitting from the good will of volunteers with no obligation to us.

That said, I've just completed an upgrade to the latest dev master, hoping that would resolve our immediate build issues and I'm sorry to report that it did not. So I assume that is why people are so hungry for a release.

And @developer239 this issue was introduced by Angular not this repository. See https://github.com/ngxs/store/issues/1974#issuecomment-1460928121.

**Comment by motabass** [comment] 2023-03-28 15:10
Hi. i can confirm that dev prerelease works fine for me when defining version like this in package.json:

`    "@ngxs/devtools-plugin": "3.7.6-dev.master-6835a28",
    "@ngxs/logger-plugin": "3.7.6-dev.master-6835a28",
    "@ngxs/router-plugin": "3.7.6-dev.master-6835a28",
    "@ngxs/store": "3.7.6-dev.master-6835a28"`

**Comment by oleg-varlamov** [comment] 2023-03-29 03:18
> Hi. i can confirm that dev prerelease works fine for me in angular@15.2.4 when defining version like this in package.json:
> 
> ```
> "@ngxs/devtools-plugin": "3.7.6-dev.master-6835a28",
> "@ngxs/logger-plugin": "3.7.6-dev.master-6835a28",
> "@ngxs/router-plugin": "3.7.6-dev.master-6835a28",
> "@ngxs/store": "3.7.6-dev.master-6835a28"
> ```
> 
> just `dev` did not work for me either

I tried today to use version "3.7.6-dev.master-6835a28" but with no success - same build error.

**Comment by internalsystemerror** [comment] 2023-03-29 11:05
My mistake, after the comments above, I decided to check and we had `^3.7.6-dev.master-6835a28` which was installing `3.7.6` instead. Pinning the dependency instead allows the installation of the correct version.

**Comment by markwhitfeld** [comment] 2023-03-29 14:13
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:13 UTC
Labels: ready to release, type: bug/fix, state: has PR, released

**Comment by markwhitfeld** [comment] 2023-05-05 11:59
For those monitoring this issue, I see that the TypeScript bug fix (that was holding our releases up) has been merged and it looks like it will be part of the next minor Typescript release!!! Fantastic news!
