### ISSUE TITLE
🐞[BUG]: Route not updated via ReduxDevTools 

### ISSUE THREAD

**Issue by bmayen** [ngxs/store#1640] opened 2020-07-03 11:27 UTC
### Affected Package 
NgxsRouterPluginModule and/or NgxsReduxDevtoolsPluginModule?

### Is this a regression?
I believe so

### Description
I have a default Angular CLI v9 app. Have added NGXS with router and devtools plugin according to the docs. When I navigate between routes, router state is updated as expected and I can see this in ReduxDevtools extension for Chrome. However, when I try to step back to previous route via devtools, the app route does not update. 

Expected behavior is "time-travel debugging" where the application updates to the route contained in the store, correct?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ngxs-router-bug

## Environment

<pre><code>
Libs:
- @angular/core version: ~9.1.11
- @ngxs/store version: ^3.6.2

Using Angular v9 because NGXS support for v10 isn't final.

Browser:
- [x] Chrome (desktop) version LATEST
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.3.0
- Platform:  Mac

**Comment by cheindl** [comment] 2020-07-09 18:56
I have the same issue.

**Comment by bmayen** [comment] 2020-07-10 15:36
Doing some further investigation today. 

When stepping backwards via ReduxDevTools, router plugin's `navigateIfNeeded` method returns false.
https://github.com/ngxs/store/blob/86c7f70aee008b1d487c3b59d7e788c4cbff3621/packages/router-plugin/src/router.state.ts#L158

This is due to `!this._storeState` evaluating to `true`.

Will continue to look into this...

**Comment by splincode** [comment] 2020-07-10 19:48
@arturovt what do you think?

@bmayen I will be happy if you create PR for fixing this bug (maybe we can use special option for migrate new your behavior for prevention breaking change)

**Comment by bmayen** [comment] 2020-07-10 21:03
I'll need some additional help in order to get this PR to you.

My first guess on a fix here is that it seems like we need a different set of conditions for `canSkipNavigation` if triggered from ReduxDevTools. Is there a way to detect this? 

Is this a sensible line of thinking for this problem?

**Comment by developer239** [comment] 2021-01-04 20:11
Any updates on this issue? This is almost a blocker for most people because it makes redux dev tools and time travel useless. 🤔

**Comment by bmayen** [comment] 2021-01-05 17:41
Agreed this is a blocker in many cases. Unfortunately, I didn't get much further on a solution without additional feedback, and my bandwidth is pretty limited these days. Maybe someone else could pick this up?

**Comment by markwhitfeld** [comment] 2022-08-08 22:25
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:25 UTC
Labels: domain: plugins, domain: core, type: feature, state: has PR, released
