### ISSUE TITLE
🚀[FEATURE]: use both sessionStorage and localStorage

### ISSUE THREAD

**Issue by scott-ho** [ngxs/store#598] opened 2018-10-09 08:17 UTC
## Feature Request
In my application, I need to use sessionStorage and localStorage to persist related data.

`storage-plugin` now only supports one storage engine.

### Versions
```
* ngxs: v3.2.0
* @angular/core: v6.0.0
```

### Repro steps
none

### Observed behavior
one storage engine supported

### Desired behavior
multi storage engine support

**Comment by YogliB** [comment] 2019-01-15 07:17
Is it possible to achieve with two custom storage engines?

**Comment by splincode** [comment] 2019-01-15 07:22
Not sure

**Comment by Senneseph** [comment] 2019-08-20 15:13
I'd like this as well, so that the storage engine can be specified within the @State decorator.  I think for most people's applications, they are going to want auth information and other application-level stores to be shared across tabs in LocalStorage as opposed to SessionStorage which would cause users to log in again with each new tab they opened.  While other information (current route, resources still in the draft stage, etc), is appropriately placed in SessionStorage - since it's data that is still only specific to a given tab.

**Comment by splincode** [comment] 2019-12-18 21:59
https://www.npmjs.com/package/@ngxs-labs/data

**Comment by markwhitfeld** [comment] 2023-03-29 14:09
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:09 UTC
Labels: domain: plugins, ready to release, type: feature, released
