### ISSUE TITLE
🐞[BUG]: console error: Error ocurred while serializing the store value, value not updated

### ISSUE THREAD

**Issue by KokalaBhanusri** [ngxs/store#1684] opened 2020-10-14 01:26 UTC
### Affected Package
 The issue is caused by package @ngxs/storage-plugin/fesm5/ngxs-storage-plugin.js

### Description

I am using ngxs store in my angular application for storage management. Recently I am seeing below weird console error in my browser when I switch between various angular components while dispatching action to store

'Error ocurred while serializing the store value, value not updated.'

I tried to explore on this but there is no proper documentation available over the internet on this.
 
## 🔥 Exception or Error
ngxs-storage-plugin.js:288 Error ocurred while serializing the store value, value not updated.
(anonymous) @ ngxs-storage-plugin.js:288
push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._next @ tap.js:45
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/ReplaySubject.js.ReplaySubject._subscribe @ ReplaySubject.js:67
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable._trySubscribe @ Observable.js:43
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject._trySubscribe @ Subject.js:89
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:29
shareReplayOperation @ shareReplay.js:42
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/tap.js.DoOperator.call @ tap.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/catchError.js.CatchOperator.call @ catchError.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
push../node_modules/rxjs/_esm5/internal/operators/tap.js.DoOperator.call @ tap.js:18
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
shareReplayOperation @ shareReplay.js:30
push../node_modules/rxjs/_esm5/internal/Observable.js.Observable.subscribe @ Observable.js:24
push../node_modules/@ngxs/store/fesm5/ngxs-store.js.InternalDispatcher.dispatch @ ngxs-store.js:1751
dispatch @ ngxs-store.js:2108

Libs:
- @angular/core version: "~8.2.14",
- @ngxs/devtools-plugin: "^3.7.0",
- @ngxs/logger-plugin: "^3.6.2-dev.master-eaa5d86",
- @ngxs/storage-plugin: "^3.7.0",
- @ngxs/store: "^3.7.0",

Same issue with 3.6.2-dev version also.

**Comment by vsarunov** [comment] 2021-02-08 22:10
Seeing the same error.

**Comment by arturovt** [comment] 2021-04-19 19:37
The storage plugin doesn't do any supernatural work, but only runs `JSON.parse(localStorage.getItem(stateName))`. It can fall into the `catch` block only if the retrieved value is an invalid string, e.g. `JSON.parse('qwerty')`.

I have expanded the error message a little bit in this PR (https://github.com/ngxs/store/pull/1727/files#diff-734503ffffdcb1dd1a7f4d04104674ba17c6cb907096ac0ef31c5a18a500720fR58-R65), thus you'll be able to see the value that storage plugin has failed to parse.

**Comment by yksht** [comment] 2021-05-31 07:54
Hello.
I get the same error in console.

Angular version: 7.2.15
Ngxs version: 3.7.2
Storage plugin version: 3.7.2
Router plugin version: 3.7.2

I've update ngxs/storage-plugin with the changes from the PR in the comment above to check what state causes the problem and it looks like the issue is in the ngxs router plugin.

I've used following storage plugin initialization:
`NgxsStoragePluginModule.forRoot({
  key: [
    <my_states>,
    'router'
  ]
}),`

And have following error message in cosole:
_Error ocurred while serializing the **router** store value, value not updated, the value obtained from the store_

Unfortunatly I failed to make a repro, this error appears only on one page in my app and only after page reload :(
I'll try to investigate deeply

**Comment by markwhitfeld** [comment] 2022-08-08 22:26
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:26 UTC
Labels: domain: plugins, domain: core, released
