### ISSUE TITLE
🐞[BUG]: State override in case of concurrent dispatch

### ISSUE THREAD

**Issue by krszktc** [ngxs/store#1728] opened 2021-03-12 20:28 UTC
### Affected Package
 @ngxs

### Description

There are three components. Two of them show data aggregated in specific, different way. Third showing potential issue with data. As for now I have two issues with data:

1. Both ComponentA and ComponentB dispatching data but ValidationComponent achieve only one message from store. I'm aware that log could be slower than action execution on store so this is 'optional issue'. Some inconvenience just to mention in margin :)

![image](https://user-images.githubusercontent.com/24602491/111193139-22d92700-85ba-11eb-845c-43e009dfc129.png)

2. This is something what makes me more problem with my data consistency. Looking at the logs above, before any interaction, status for StatusState is **{id: "id-2", status: "valid"}**. And now when you click "BAD" button which simulate data with validation issue, app status looks like on screen below. 

Doesn't matter if I'm using async/await, pipe(tap()) or just subscribe to service in DataState, all the time I'm getting one extra emission in ValidationComponent which looks to be some kind of snapshot of data, before dispatch from componentsA/B. Log can be broken - ok, but at the end data in components are inconsistent.

I found some temporary workaround where if I dispatch one extra action from DataState it's working as I expect ... but being hones I have not idea why.

![image](https://user-images.githubusercontent.com/24602491/111196229-55385380-85bd-11eb-987c-3acbadad4266.png)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-ph8qwv
   

## Environment
<pre><code>
Libs:
    "@ngxs/devtools-plugin": "^3.6.2",
    "@ngxs/logger-plugin": "^3.6.2",
    "@ngxs/store": "^3.6.2",

Browser:
- [x] Chrome (desktop) version  88.0.4324.190
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.7.0
- Platform:  Linux, Windows

</code></pre>

**Comment by VitaliyFilatov** [comment] 2021-09-22 11:41
trick with setTimeout with 0 delay is help to solve the problem

**Comment by VitaliyFilatov** [comment] 2021-09-22 11:54
it reproduce with one component https://stackblitz.com/edit/angular-ivy-otxvqt?file=src/app/one.component.ts

**Comment by markwhitfeld** [comment] 2022-08-05 21:09
Oh wow!!! I think I finally understand this issue.
Here is my improved repro: https://stackblitz.com/edit/angular-ivy-teh5xo?file=src%2Fapp%2Fone.component.ts%3AL61-L65

**Comment by markwhitfeld** [comment] 2022-08-05 22:19
Ok, simplified it even more: https://stackblitz.com/edit/angular-ivy-3jgjkk?file=src%2Fapp%2Fapp.component.ts%3AL69-L73
This is definitely a bug to do with how rxjs is handling modifications to the behavior subject when there are still observers pending notification. We will look into it ASAP.

**Comment by markwhitfeld** [comment] 2022-08-08 22:27
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:27 UTC
Labels: domain: core, priority: high, type: bug/fix, released

**Comment by krszktc** [comment] 2022-08-09 15:45
Hey @markwhitfeld 
Thanks for checking that. The issue was quite tricky but I'm glad that you found a root cause.
