### ISSUE TITLE
ngxsOnInit is not working when importing modules in "wrong" order

### ISSUE THREAD

**Issue by hboelke** [ngxs/store#539] opened 2018-08-09 12:32 UTC
### Versions
```
* ngxs: 3.2.0
* @angular/core: 6.1.0
```

### Observed behavior

The function `` ngxsOnInit `` don't get called when loading the store with  `` ngxsModule.forFeature() `` in a module that was imported before `` NgxsModule.forRoot() `` was imported.

Everything works like expected, except the `` ngxsOnInit`` function.

Importing modules that uses ngxs after `` NgxsModule.forRoot() `` solves the problem, but could cause problems if you don't know it.

**Comment by aziznatour** [comment] 2018-08-09 18:40
@devs If this is intentional, then at the very least it should be mentioned in the official documentations

**Comment by juliusstoerrle** [comment] 2018-08-18 17:07
Duplicate of https://github.com/ngxs/store/issues/375

**Comment by splincode** [comment] 2019-07-23 10:02
Released in 3.5.0

**Closed by splincode** 2019-07-23 10:02 UTC
Labels: domain:core, ready to release
