### ISSUE TITLE
@ngxs/form-plugin state updates after submit

### ISSUE THREAD

**Issue by OvidijusStukas** [ngxs/store#365] opened 2018-05-08 05:49 UTC
### Versions
@ngxs 3.0.1

```
* ngxs:
* @ngxs/form-plugin
```

### Repro steps

1. Create an angular form with 'updateOn' set to submit.
2. Change input values
3. Submit form

### Observed behavior
Redux dev tools log:
![image](https://user-images.githubusercontent.com/9720553/39740020-71a0100a-529c-11e8-9884-6bc7ab3bdeb1.png)

Console output:
![image](https://user-images.githubusercontent.com/9720553/39740033-7d21a24a-529c-11e8-8944-2a0c3e3c6b2b.png)

As you can see Angular correctly updates events, firstly sends value change event then sends ngSubmit event.

But forms plugin updates form only after submit event was fully handled.

### Desired behavior
Forms plugin to act and handle events like Angular and update values on value changes, not after form was submitted.

### Mention any other details that might be useful (optional)

Login action is sent in ngSubmit event handler.

Also tried to set ngxsFormDebounce to 0 on the form, thinking it was the debouce that helt the updates to state but this did not help.

**Comment by tsawan** [comment] 2018-05-22 17:57
@OvidijusStukas forms plugin handles update using angular's valueChanges so if you use updateOn to Submit, then how do you expect forms plugin to update the store on value changes?

Please elaborate further if I am missing something.

**Comment by FortinFred** [comment] 2018-08-13 20:27
One would set the updateOn to submit in order to "delay" validation.  Unfortunately, it also differs the actual modification of the model values.

In an ideal world, Angular would introduce a validateOn FormHook which wouldn't affect the "updateOn".

**Comment by FortinFred** [comment] 2018-09-25 20:40
I've written a stackblitz to expose a potential problem.
https://stackblitz.com/edit/ngxs-simple-bslj5w

In my current situation, I have a navigation-handler that will change route upon sucess of the SubmitForm action.

My form is "updateOn: blur".  

**Steps to reproduce:**
Make sure to open the console to withness the formGroup valueChanges
Fill in the first name
Fill in the last name
Fill in the age and directly click the "Submit" button. 

The age's value is shown in the console but the state is not updated because the update actions were not triggered.

**Comment by FortinFred** [comment] 2018-09-25 21:06
Ok, looking more closely, I was able to fix my issue with the blur event by putting ngxsFormDebounce="0" on my form.

Sadly, it does not work for the updateOn: "submit"

**Comment by FortinFred** [comment] 2019-05-16 19:23
I think that even at 0 rxjs.debounceTime delays the execution:

https://stackoverflow.com/questions/53674718/rxjs-debouncetime0-still-postpones-execution

**Comment by FortinFred** [comment] 2019-05-17 09:50
After investigation, I've narrowed the issue down to two things:
- ngxsForm's debounceTime operator will always introduce an async dispatch of updateForm* actions
- Angular's formControls are not updated upon submit when using "updateOn":"blur |   ##submit"
https://github.com/angular/angular/issues/26683

I'm currently using 'blur' for my form so I was able to get around Angular's issue by focusing on the submit button before processing the actual commit.

As for NGXS, removing the debounceTime for 'blur | submit' forms does the trick.

**Comment by markwhitfeld** [comment] 2019-05-17 21:25
Merged, and part of the latest `@dev` version. Would it be possible to test it out?

**Comment by FortinFred** [comment] 2019-05-17 21:54
@markwhitfeld 
It works!

With version 3.4.3
https://stackblitz.com/edit/ngxs-simple-exjqcr

With version 3.4.3-dev.master-29776a7
https://stackblitz.com/edit/ngxs-simple-fmtxuw

**Comment by splincode** [comment] 2019-07-23 10:01
Released in 3.5.0

**Closed by splincode** 2019-07-23 10:01 UTC
Labels: domain:plugins, ready to release
