### ISSUE TITLE
🐞[BUG]: Uncaught TypeError: Cannot redefine property: ɵfac

### ISSUE THREAD

**Issue by xutzin** [ngxs/store#1855] opened 2022-06-10 07:40 UTC
### Affected Package

@ngxs/store

### Is this a regression?

Yes, the previous version in which this bug was not present was: 3.7.3

### Description

1. Either removing the inheritance `extends ShaBaseDialog` or commenting out `@Select(...) account$` can make the errors go away
2. Switching back to 3.7.3 can fix the issue, too

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-vgtlgq

`$ ng test @shared/error`

## 🔥 Exception or Error
<pre><code>
10 06 2022 15:20:31.975:INFO [launcher]: Starting browser Chrome
10 06 2022 15:20:33.966:INFO [Chrome 102.0.5005.115 (Windows 10)]: Connected on socket X59I98ybWDev5CwuAAAB with id 96706161        
Chrome 102.0.5005.115 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot redefine property: ɵfac
  TypeError: Cannot redefine property: ɵfac
      at Function.defineProperty (<anonymous>)
      at addDirectiveFactoryDef (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25268:12)
      at compileComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25015:5)     
      at typeFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25481:158)
      at TypeDecorator (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:3842:21)        
      at __decorate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:58:54)
      at Object.784 (http://localhost:9876/_karma_webpack_/webpack:/projects/shared/error/src/lib/dialog/main/main.dialog.ts:13:30) 
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.7262 (http://localhost:9876/_karma_webpack_/main.js:43:70)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
Chrome 102.0.5005.115 (Windows 10): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome 102.0.5005.115 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot redefine property: ɵfac
  TypeError: Cannot redefine property: ɵfac
      at Function.defineProperty (<anonymous>)
      at addDirectiveFactoryDef (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25268:12)
      at compileComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25015:5)     
      at typeFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:25481:158)
      at TypeDecorator (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:3842:21)        
      at __decorate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/tslib/tslib.es6.js:58:54)
      at Object.784 (http://localhost:9876/_karma_webpack_/webpack:/projects/shared/error/src/lib/dialog/main/main.dialog.ts:13:30) 
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.7262 (http://localhost:9876/_karma_webpack_/main.js:43:70)
Chrome 102.0.5005.115 (Windows 10): Executed 0 of 0 ERROR (0.026 secs / 0 secs)
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 14.0.1
- @ngxs/store version: 3.7.4

Browser:
- [x ] Chrome (desktop) version 102.0.5005.115 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v16.15.1 (LTS)
- Platform: Windows 

Others:
-
</code></pre>

**Comment by MichaelAlt** [comment] 2022-06-10 13:10
Got the same issue. Only happens during testing. Works fine in build and development. When i use the store everything works. If i use the @Select annotation than it fails.

**Comment by xutzin** [comment] 2022-06-10 13:43
I'm not sure if it's the same issue, but in my case there's another issue encountered during runtime.
```
Uncaught TypeError: Cannot set property ɵfac of function OrxUserNgXsState(<omitted>... } which has only a getter
    at 80341 (user.ngxs.state.ts:23:2)
    at __webpack_require__ (bootstrap:19:1)
    at 73844 (inventory.ngxs.actions.ts:12:2)
    at __webpack_require__ (bootstrap:19:1)
    at 79878 (main.js:16:93)
    at __webpack_require__ (bootstrap:19:1)
    at 26746 (app.component.html:3:15)
    at __webpack_require__ (bootstrap:19:1)
    at 28940 (environment.ts:17:71)
    at __webpack_require__ (bootstrap:19:1)
```

**Comment by markwhitfeld** [comment] 2022-06-12 19:33
Thank you for the thorough bug report!
@arturovt is having a look into it.
If anyone is experiencing this issue as well, then please mention your Angular version just in case that is relevant.

**Comment by mart-dominguez** [comment] 2022-06-14 19:32
I am having the same issue
Libs:
- @angular/core version: 11.2.14
- @ngxs/store version: 3.7.4

**Comment by andrioid** [comment] 2022-06-14 19:46
Same here, Angular 13 and ngnx/store 3.7.4. Forcing version to 3.7.3 made tests runable again.

**Comment by XardasLord** [comment] 2022-06-15 09:55
I have the following issue with 3.7.4 but 3.7.3 of @ngxs/store as well:
```
Error: node_modules/@ngxs-labs/actions-executing/lib/actions-executing.module.d.ts:7:97 - error TS2339: Property 'ɵbc' does not exist on type 'typeof import("C:/localRepositories/NHIA/Eclaims 2.0/eclaims.vetting.client/eclaims-vetting/node_modules/@ngxs/store/ngxs-store")'.

7     static ɵmod: ɵngcc0.ɵɵNgModuleDeclaration<NgxsActionsExecutingModule, never, [typeof ɵngcc1.ɵbc], never>;

```

**Comment by eduard9x** [comment] 2022-06-15 10:50
I am not sure if this helps, but for me it started happening after upgrading from angular 12.2.9 to angular 12.2.16, but @ngxs/store: 3.7.1 remained the same.

I am getting the same runtime error.
[what [xutzin](https://github.com/xutzin) said on #1.](https://github.com/ngxs/store/issues/1855#issuecomment-1152378566)

After recreating the components I found that if I comment out the `@Select` from my base method, the problem would go away.

**Comment by arturovt** [comment] 2022-06-21 14:57
@xutzin are you able to install the `3.7.4-dev.master-310a613` version and give it a try?

**Comment by xutzin** [comment] 2022-06-22 06:44
Thank you all for taking the time on this issue.

I tried version `3.7.4-dev.master-310a613` and the results are as follows:

| Branch<br/>(https://github.com/xutzin/angular-ngxs)  | NgXs Version | Error encountered during test<br/>Cannot redefine property: ɵfac | Error encountered during runtime<br/>Cannot set property ɵfac of ... |
| --- | --- | --- | --- |
| master | 3.7.3 |  |  |
| issue-3.7.4-cannot-set-property-fac | 3.7.4 | x | x |
| issue-3.7.4-dev-cannot-set-property-fac | 3.7.4-dev.master-310a613 |   | x |

**Comment by mcrtricolor** [comment] 2022-07-19 03:06
> After a lengthy discussion, we decided to deprecate the Select decorator since it has impossible bugs to fix (just because Angular itself doesn't allow it). We're also planning to drop it in the future. It's complicated to maintain since we have to invest a lot of time into a single Select decorator rather than focusing on other essential issues. It's not type-safe. It has problems in server-side rendering and module federation. We tried to fix the server-side rendering issue initially, leading to a dead end.
> 
> For now, start replacing the Select decorator with `store.select`. You also shouldn't have any issues with `3.7.4` if you drop Select decorator usages.

Hi, i'm having the same problem. Could you give me an example of how to do this switch between the Select decorator and the store.select?

I currently use it like this:

_@Select(SesionState.getSesion)
 sesion$: Observable<Sesion>;_

And then access it like this:

_this.sesion$.pipe( takeUntil(this.unsubscribeBase)) .subscribe(
sesion => {     

// Do stuff

});_

Thanks!

**Comment by axel-zarate** [comment] 2022-07-19 03:54
@mcrtricolor 
```
constructor(store: Store) {
    this.session$ = store.select(SesionState.getSesion);
    
    // Use `this.session$` as you would when using @Select
}
```

If you are not referencing the `session$` property in the template or in your component code, you could directly do:

```
store.select(SesionState.getSesion).pipe(takeUntil(this.unsubscribeBase)).subscribe(sesion => {
    // Do stuff
});
```

**Comment by mcrtricolor** [comment] 2022-07-19 13:34
Thanks axel! It was a big change in the app but it worked!

Thanks again for your quick response.

**Comment by markwhitfeld** [comment] 2022-08-08 22:33
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

Also, a specific note regarding this issue: Our recommendation to move away from the decorator still stands but we decided to only introduce the deprecation message in v3.8 because we will be providing a cleaner alternative to the decorator that does not require injecting the store.

**Closed by markwhitfeld** 2022-08-08 22:33 UTC
Labels: domain: core, ready to release, priority: critical, type: bug/fix, angular:ivy, released
