### ISSUE TITLE
🐞[BUG]: Storage plugin does not work with lazy state

### ISSUE THREAD

**Issue by BlindDespair** [ngxs/store#1877] opened 2022-07-14 22:50 UTC
### Affected Package

The issue is caused by package `@ngxs/store` and `@ngxs/storage-plugin`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 2.0.0-rc.24

### Description

 
When using `@ngxs/storage-plugin` with lazy loaded state the state loaded from local storage gets overriden by initialization of lazy module.
![image](https://user-images.githubusercontent.com/15785773/179097288-dbac62eb-9975-4f51-8760-06d031d837bf.png)
e.g. here I have `count: 7` persisted in local storage and on `@@INIT` it is set correctly.
But after that comes `@@UPDATE_STATE` and resets it back to default 🤯 
![image](https://user-images.githubusercontent.com/15785773/179097465-b7e11109-85aa-4ed7-801e-973dac5d8777.png)

I saw exactly the same issue being solved in #122 and it seems like it's been reintroduced again.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-xg8iqd

## Environment

<pre><code>
Libs:
- @angular/core version: 14.0.0
- @ngxs/store version: 3.7.4

Browser:
- [x] Chrome (desktop) version 103.0.5060.114
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.15.0  
- Platform:  Windows

**Comment by BlindDespair** [comment] 2022-07-15 11:24
One note for those encountering this issue now:
it works if you specify the keys for states, even if you want to have the whole state persisted, like this:
```
NgxsStoragePluginModule.forRoot({key: [LazyState]}),
```
So this can be a decent workaround, but I believe it should work properly when persisting the whole state.

**Comment by arturovt** [comment] 2022-07-30 12:41
Confirmed. This is a duplicate of #1857 .

**Closed by arturovt** 2022-07-30 12:41 UTC
