### ISSUE TITLE
NgxsRouterPluginModule.forRoot() compiles in Angular 8 but UI does not displays

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs/store#1130] opened 2019-06-16 15:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

With the following AppModule, the application is NOT displayed:
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { SharedMainModule } from '@medsoft/common/shared-main';
import { NgxsDispatchPluginModule } from '@ngxs-labs/dispatch-decorator';
import { NgxsEmitPluginModule } from '@ngxs-labs/emitter';
import { NgxsFormPluginModule } from '@ngxs/form-plugin';
import { NgxsRouterPluginModule } from '@ngxs/router-plugin';
import { NgxsModule } from '@ngxs/store';

import { AppComponent } from './app.component';

const modules = [
  SharedMainModule
];

@NgModule( {
             declarations: [ AppComponent ],
             imports: [
               NgxsModule.forRoot( [] ),
               BrowserModule,
               NgxsDispatchPluginModule.forRoot(),
               NgxsEmitPluginModule.forRoot(),
               NgxsFormPluginModule.forRoot(),
               NgxsRouterPluginModule.forRoot()
             ],
             providers: [],
             bootstrap: [ AppComponent ]
           } )
export class AppModule {}
```

## Expected behavior
The application should be displayed with NgxsRouterPluginModule.forRoot() uncommented. With NgxsRouterPluginModule.forRoot() commented, the application is displayed

## Minimal reproduction of the problem with instructions

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { SharedMainModule } from '@medsoft/common/shared-main';
import { NgxsDispatchPluginModule } from '@ngxs-labs/dispatch-decorator';
import { NgxsEmitPluginModule } from '@ngxs-labs/emitter';
import { NgxsFormPluginModule } from '@ngxs/form-plugin';
import { NgxsRouterPluginModule } from '@ngxs/router-plugin';
import { NgxsModule } from '@ngxs/store';

import { AppComponent } from './app.component';

const modules = [
  SharedMainModule
];

@NgModule( {
             declarations: [ AppComponent ],
             imports: [
               NgxsModule.forRoot( [] ),
               BrowserModule,
               NgxsDispatchPluginModule.forRoot(),
               NgxsEmitPluginModule.forRoot(),
               NgxsFormPluginModule.forRoot(),
               NgxsRouterPluginModule.forRoot()
             ],
             providers: [],
             bootstrap: [ AppComponent ]
           } )
export class AppModule {}
```

## Environment

<pre><code>
Libs:
- @angular/core version: 8.0.1
- @ngxs/store version: 3.4.3

Browser:
- [X ] Chrome (desktop) Version 77.0.3827.0 (Official Build) canary (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.3.1
- Platform:  Windows  10

Others:
IDE Webstorm, 
package manager, Yarn

**Comment by arturovt** [comment] 2019-06-16 15:41
Would be great if you create a repo with reproduction.

**Comment by arturovt** [comment] 2019-06-16 16:29
Provide a reproduction. Those steps, that you've mentioned, are not clear instructions. What is `@medsoft/common/shared-main`?

**Comment by arturovt** [comment] 2019-06-16 16:38
My application uses Angular 8 version along with `@ngxs/router-plugin` and it works perfectly.

**Comment by st-clair-clarke** [comment] 2019-06-18 11:46
You can comment @mdesoft/common/shared and related code - the problem still exist.

**Comment by splincode** [comment] 2019-06-18 11:53
@st-clair-clarke please share repo for reproduce or stackblitz example

**Comment by arturovt** [comment] 2019-06-18 12:42
@st-clair-clarke as you can see my previous comment - I use Angular 8 and router plugin, and it works without any issues. I need a reproduction to see what's going wrong

**Comment by splincode** [comment] 2019-06-23 18:11
The error is reproduced, since I upgraded to Angular 8 and SSR does not work for us.
https://github.com/ngxs/store/pull/1136

**Comment by arturovt** [comment] 2019-07-24 20:20
@st-clair-clarke @splincode Could one of you make a reproduction? Because currently this issue is frozen and we're not able to move forward.

P.S. I don't even know what error is there, this would let me to go into router plugin and give me a chance to fix it :)

**Comment by splincode** [comment] 2019-07-24 20:27
I can't reproduce

**Comment by arturovt** [comment] 2019-07-27 16:13
@st-clair-clarke are you able to do a reproduction for us? Because I'm not sure if our team can resolve this issue w/o a reproduction, I will close it ASAP.

**Comment by arturovt** [comment] 2019-08-01 17:53
Closing this issue until we get some reproduction so we're able to de-escalate this problem.

**Closed by arturovt** 2019-08-01 17:53 UTC
Labels: domain:plugins
