### ISSUE TITLE
🐞[BUG]: Multiple actions dispatched with async action handlers are not executed in order 

### ISSUE THREAD

**Issue by Hacklone** [ngxs/store#1709] opened 2020-12-15 12:53 UTC
### Affected Package
@ngxs/store

### Is this a regression?
No

### Description

If multiple actions are dispatched with asynchronous action handlers, then these action handlers are not executed in order.
If these action handlers mutate the same property of the state then the result may be not what the action dispatcher would expect.

## 🔬 Minimal Reproduction

```typescript
export class ActionA {
  static readonly type = 'Action A';
}

export class ActionB {
  static readonly type = 'Action B';
}

@State<PageStateModel>({
  name: 'pageState',
  defaults: {
    fruit: null, 
  },
})
@Injectable()
export class PageState {
  @Action(ActionA)
  public async handleAAsync(ctx: StateContext<PageStateModel>) {
    await waitForMillisecondsAsync(10000);

    ctx.patchState({
      fruit: 'apple',
    });
  }

  @Action(ActionB)
  public async handleBAsync(ctx: StateContext<PageStateModel>) {
    await waitForMillisecondsAsync(10);

    ctx.patchState({
      fruit: 'banana',
    });
  }
}

export class MyComponent {
  constructor(private _store: Store) {}

  public buttonClick() {
    // we're waiting for all actions to finish
    await this._store.dispatch([new ActionA(), new ActionB()]).toPromise();

    // I would expect 'banana' since ActionB runs later but this will log 'apple' 
    console.log(this._store.snapshot().pageState.fruit);
  }
}
```

I think the problem will be the `forkJoin` in `store/packages/store/src/internal/dispatcher.ts: dispatchByEvents()` as it doesn't wait for the actions to finish before executing the next.

**Comment by Hacklone** [comment] 2020-12-15 12:53
If you agree that this is a bug, I can spin up a PR to fix it... :)

**Comment by Hacklone** [comment] 2020-12-15 12:58
Until then his is a workaround ;) 
```
await this._store.dispatch(new ActionA()).toPromise();
await this._store.dispatch(new ActionB()).toPromise();
```

**Comment by arturovt** [comment] 2021-06-10 21:30
I am closing this as it's not an issue, and it's working as designed. NGXS should always handle actions in "parallel". The NgRx effects are behaving in the same way.

In your scenario it's worth having 1 action that dispatches another action internally:
```ts
export class PageState {
  @Action(ActionA)
  async handleAAsync(ctx: StateContext<PageStateModel>) {
    await waitForMillisecondsAsync(10000);

    ctx.patchState({
      fruit: 'apple'
    });
  }

  @Action(ActionB)
  async handleBAsync(ctx: StateContext<PageStateModel>) {
    await waitForMillisecondsAsync(10);

    ctx.patchState({
      fruit: 'banana'
    });

    await ctx.dispatch(new ActionA()).toPromise();
  }
}
```

There's no way to know for the store if action depends on another action since actions can be "cross-state", e.g. action from 1 state dispatches actions that are handled by other states.

**Closed by arturovt** 2021-06-10 21:30 UTC
