### ISSUE TITLE
🐞[BUG]: selectOnce and selectSnapshot differs

### ISSUE THREAD

**Issue by chabb** [ngxs/store#1881] opened 2022-07-20 13:29 UTC
### Affected Package

The issue is caused by package @ngxs/store

### Is this a regression?

Yes, it was working on 3.7.3

### Description

`selectOnce()` does not return the same value as `selectSnapshot()`

## 🔬 Minimal Reproduction
On 3.7.3, this codes behaves correctly : https://stackblitz.com/edit/ngxs-repro-8py9ou 
You can look at the console statements, the values match

On 3.7.4, the values do not match anymore
https://stackblitz.com/edit/ngxs-repro-pgaatt

Also, if you switch  `selectOnce` with  `select`, you'll see that it seems to replay the change of the store. It seems to be related to this bug, and I do not think it was the case before

**Comment by chabb** [comment] 2022-07-21 06:10
Probably the same root cause as #1880

**Comment by arturovt** [comment] 2022-07-23 21:39
Closing as duplicate of #1880.

**Closed by arturovt** 2022-07-23 21:39 UTC
