### ISSUE TITLE
HMR plugin is not working

### ISSUE THREAD

**Issue by joaqcid** [ngxs/store#887] opened 2019-03-02 20:05 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
After following documentation to implement hmr plugin, its not working. When making changes i get the following error "Error: The selector "app-root" did not match any elements" 

## Expected behavior
After hot reloads, there should be no error and changes should be reflected

## Minimal reproduction of the problem with instructions
https://github.com/joaqcid/ngxs-hmr

## What is the motivation / use case for changing the behavior?
N/A

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.0
- @ngxs/store version: 3.4.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X] Chrome (iOS) version 72.0.3626.119
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.1
- Platform: Mac

Others:
</code></pre>

**Comment by markwhitfeld** [comment] 2019-03-04 10:20
@splincode This is the isue we saw with NG 5.
It is working perfectly with my production project. Not sure what the issue is here.

**Comment by MylesShannon** [comment] 2019-03-06 17:31
I'm having the exact same issue. I followed the NGXS written tutorial for adding HMR support to my existing application. When I serve with HMR successfully and then make a component template change, HMR sees the update as expected, but I get a similar error in Chrome's console as @joaqcid 

<img width="651" alt="screen shot 2019-03-06 at 12 27 14 pm" src="https://user-images.githubusercontent.com/1764391/53900910-93343180-400b-11e9-95fa-c48901d96914.png">

**Comment by splincode** [comment] 2019-03-11 16:26
Try install new Dev version

```
$ npm install @ngxs/hmr-plugin
```

**Comment by joaqcid** [comment] 2019-03-11 18:17
> Try install new Dev version
> 
> ```
> $ npm install @ngxs/hmr-plugin@dev
> ```

worked!

**Comment by markwhitfeld** [comment] 2019-03-14 08:12
The fix has been released in v3.4.3!
Please test and confirm that it is working as expected.

**Closed by markwhitfeld** 2019-03-14 08:12 UTC
Labels: regression

**Comment by MatissJanis** [comment] 2019-10-28 14:00
I'm experiencing the same issue in 3.5.1.
![Screenshot 2019-10-28 at 16 00 12](https://user-images.githubusercontent.com/886567/67684556-1429aa00-f99c-11e9-8d56-b5d6fc66c8d0.png)

**Comment by splincode** [comment] 2019-10-28 14:10
Please create repo for reproduce

**Comment by markwhitfeld** [comment] 2019-10-29 11:13
@MatissJanis Could you report this as a separate issue because it seems to be Ivy related. It would be good to track it on its own. (Please provide a repo for reproduction too)
