### ISSUE TITLE
🐞[BUG]: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY after upgrading to 3.7.4

### ISSUE THREAD

**Issue by mojesto** [ngxs/store#1873] opened 2022-06-30 07:06 UTC
### Affected Package

 The issue is caused by package @ngxs/3.7.4

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 3.7.3

### Description

 After upgrading to 3.7.4 getting error 'No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY', although the token is used only in the ngxs store module configuration

## 🔬 Minimal Reproduction
<pre><code>
NgxsModule.forRoot([GlobalState], {
    selectorOptions: {suppressErrors: false, injectContainerState: false},
    developmentMode: !environment.production,
}),
</code></pre>

Usual configuration which worked well with the version 3.7.3 breaks application after upgrading to 3.7.4. 

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): NullInjectorError: NullInjectorError: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY!
NullInjectorError: NullInjectorError: No provider for InjectionToken USER_PROVIDED_NGXS_EXECUTION_STRATEGY!
    at NullInjector.get (core.mjs:9081:27)
    at R3Injector.get (core.mjs:9248:33)
    at R3Injector.get (core.mjs:9248:33)
    at R3Injector.get (core.mjs:9248:33)
    at Object.factory (ngxs-store.js:465:44)
    at R3Injector.hydrate (core.mjs:9343:35)
    at R3Injector.get (core.mjs:9237:33)
    at NgModuleRef.get (core.mjs:22399:33)
    at R3Injector.get (core.mjs:9248:33)
    at injectInjectorOnly (core.mjs:4868:33)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26505:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
handleError @ core.mjs:6402
</code></pre>

## Environment

Libs:
- @angular/core version: 14.0.3
- @ngxs/store version: 3.7.4

with angular 14.0.0 getting the same error

Browser:
- [ x] Chrome (desktop) version 103.0.5060.53 (Official Build) (x86_64)
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.15.1
- Platform:  Mac

**Comment by mojesto** [comment] 2022-06-30 08:51
Application breaks after update to the next minor version. I do not know the reason, investigating, thanks.

**Comment by Allmantool** [comment] 2022-07-06 22:14
Had the same issue. 

For me it was solve by:
* Move NgxsModule.forRoot([]) imports with empty state initialization to bootstrap module.
* Leverage NgxsModule.forFeature([CurrencyRatesState]) imports with dedicated state initialization in lazy  loaded feature modules

Not sure about root cause of the issue, but it can be related to lazy loading
It looks. like injector just not have necessary token in time
![image](https://user-images.githubusercontent.com/16443259/177652301-d8fcb6cd-184b-466f-aa1a-d68734fb8958.png)

**Comment by arturovt** [comment] 2022-07-23 21:40
Closing as not reproducible.

**Closed by arturovt** 2022-07-23 21:40 UTC

**Comment by isochronous** [comment] 2024-05-16 15:41
@mojesto Did you ever figure out the issue?  I'm having the same problem now and I've already done what @Allmantool suggested.

**Comment by moohkooh** [comment] 2024-09-05 13:29
I get a similar issue with ROOT_OPTIONS:
No provider for InjectionToken ROOT_OPTIONS! im at Object.NgxsConfig_Factory [as factory] (1598.js:90311:115). Its Angular 15.2.9 and ngxs/store 3.8.2

**Comment by raktam99** [comment] 2025-01-26 15:44
I don't know if you solved it yet, but for me "provideStore()" was missing from the providers array in main.ts

**Comment by Shaybush** [comment] 2025-03-09 09:24
hey I'm facing with same issue.. 
Once I ran unit test by jest I got this error - "No provider for InjectionToken CUSTOM_NGXS_EXECUTION_STRATEGY" 
any ideas how to solve it I already provide - "provideStore()"

**Comment by isochronous** [comment] 2025-03-11 14:48
I had to add NgxsModule.ForRoot([States, To, Load]) in my unit test imports
