### ISSUE TITLE
@Selector() State Parameter is undefined with v3.5.0

### ISSUE THREAD

**Issue by wakawaka54** [ngxs/store#1218] opened 2019-08-08 06:27 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
A `@Selector()` is receiving the `state` parameter as undefined, other `@Selector()`s in the same Store class are not receiving the `state` as undefined.

```
export class ApplicationState implements NgxsOnInit {
  @Selector([ApplicationState])
  static getLocale(state: ApplicationStateModel) {
    return state.locale;
  }

  @Selector([ApplicationState])
  static getWindowState(state: ApplicationStateModel) {
    return state.window;
  }
  
  ngxsOnInit(ctx?: StateContext<ApplicationStateModel>): void {
         // some initialization code
  }
}
```

`getLocale` is called with `state` as undefined while `getWindowState` is called with `state` defined properly.

The only thing I can think of is that several other parts of the application subscribe to the ApplicationState.getLocale selector potentially before the store is ready?

## Expected behavior
Expect that the `state` parameter is defined and passed in to the selector.

## Minimal reproduction of the problem with instructions
I'll try to reproduce it in a smaller application soon.

## What is the motivation / use case for changing the behavior?
During application initialization many components need the Locale state information.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.11
- @ngxs/store version: 3.5.0

Browser:
- [x] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform:  Mac

Others:

</code></pre>

**Comment by splincode** [comment] 2019-08-08 06:54
Please add stackblitz repo for reproduce

**Comment by markwhitfeld** [comment] 2019-08-13 06:31
Closing until a Reproduction is provided.

**Closed by markwhitfeld** 2019-08-13 06:31 UTC

**Comment by zakton5** [comment] 2019-08-20 18:05
I'm having the same issue. Just downgraded to `3.4.3` and it works again. Please reopen.
@wakawaka54 Can you make a stackblitz?

**Comment by arturovt** [comment] 2019-08-20 18:12
@zakton5 we can't reopen until reproduction is provided. I'm using `3.5.0` and it's OK.

**Comment by PierreDuc** [comment] 2019-10-16 11:36
This is caused by this [fix](https://github.com/ngxs/store/commit/6d85ccb371ee8969c8bd6718e4540713ffb48ee7) which will make sure the errors in your selector are not suppressed by ngxs.

You can fix this error by changing the order of states passed to `NgxsModule.forRoot([])`, or the order of the module import in the app, thus making sure that you do not call a Selector before its state has been imported. 

Or you can try to check inside your selector to see if the state is undefined, to prevent the error.

Or you can update the `selectorOptions` to suppress the errors (which might result in hard to locate unwanted behaviour/issues in your app):

```
NgxsModule.forRoot([TasksState], {
  developmentMode: true,
  selectorOptions: { suppressErrors: true}
});
```

**Comment by Delubear** [comment] 2023-04-05 18:54
Im working on an upgrade to Angular 15 and updated NGXS to 3.8.0 and the 
`@Select(MySelectors.Selector) property$!: Observable<myType>; `
are all returning undefined.  I can directly call the store with that same selector and assign it to a property and it works just fine however.
`let property = this.store.select(MySelectors.Selector);`

Tried toggling the selector options in appModule with no change.

**Comment by markwhitfeld** [comment] 2023-04-05 21:05
I think that you are experiencing a bug caused by typescript when you target ES2022:
https://github.com/microsoft/TypeScript/issues/52004

This comment gives a better explanation of the TS issue:
https://github.com/ngxs/store/issues/1818#issuecomment-1440784120

I would recommend targeting ES2021 until this TS bug is fixed.

**Comment by markwhitfeld** [comment] 2023-05-05 12:00
PS. @Delubear , I see that the TypeScript bug fix (that was was causing your issue) has been merged and it looks like it will be part of the next minor Typescript release!!! Fantastic news!
