### ISSUE TITLE
🐞[BUG]: Cannot modify state in ngxsOnInit when using NgxsStoragePlugin and NgxsRouterPlugin

### ISSUE THREAD

**Issue by AlexCleggett** [ngxs/store#1146] opened 2019-07-05 05:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Any changes to the state made in the ngxsOnInit function are being overridden when using the router plugin and the storage plugin. Changes are not being persisted from the ngxsOnOnit function and all the persisted states are being rehydrated when the UpdateState action is handled by the storage plugin.

## Expected behavior

The router plugin or any other lazy loaded module should not cause the other states to be rehydrated from the storage engine. The router state itself is not part of the persisted states, so there should be no rehydrating at all when the UpdateState action is handled. Changes to state using patchState or setState in the ngxsOnInit function should persist.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-simple-7pydiq

The ngxsOnInit function is resetting the count to -1.
1. Hit the 'click me' button several times to increase the count
1. Refresh the page.
1. Notice that the count is the same as before the page was refreshed and is not -1 like expected.
1. Try this again, but this time comment out the NgxsRouterModule import in the app module.

Notice that the count will now be -1 as expected, however the value saved in local storage does not reflect this.

## What is the motivation / use case for changing the behavior?

Cannot modify state in ngxsOnInit when using the router plugin and the storage plugin.

## Environment

<pre><code>
Libs:
- @angular/core version: 3.4.3
- @ngxs/store version: 3.4.3
- @ngxs/router-plugin version: 3.4.3
- @ngxs/storage-plugin version: 3.4.3

Browser:
- [X] Chrome (desktop) version 75
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

## Notes

Storage plugin 'handle' method is called with the InitState action, which in turn reads in all keys from the storage engine. The ngxsOnInit lifecycle hook is then called, allowing changes to be made to the state. The storage plugin 'handle' method is called again, this time with the UpdateState action, which is for the router plugin and then again will read in the state for all keys from the storage engine. Note that the router key was not specified in the keys provided to the storage plugin module, however the storage plugin will rehydrate all states again, overriding any changes made in ngxsOnInit. 

The router plugin appears to be treated as a lazy loaded module, why is it rehydrating all the other persisted states?
The router state itself is not part of the persisted states, so it should not be rehydrating at all.
The changes made in the ngxsOnInit function are not persisted to local storage although they are expected to be, even without the router plugin being used.

**Comment by dgutoryan** [comment] 2020-03-29 21:45
I have the similar issue.
```
  ngxsAfterBootstrap(ctx: StateContext<AppStateModel>) {
    if (ctx.getState().isAuthenticated) {
      ctx.dispatch(new FetchAuthenticatedUser());
    }
  }
```
```
  @Action(FetchAuthenticatedUser)
  fetchAuthenticatedUser(ctx: StateContext<AppStateModel>) {
    ctx.patchState({ isLoading: true });
    const userId = ctx.getState().session.id;
    console.log('FetchAuthenticatedUser');

    return this.profileService.getProfile(userId).pipe(
      tap(response => ctx.patchState({ user: response.data })),
      finalize(() => {
        console.log('finalize');
        ctx.patchState({ isLoading: false });
      }),
    );
  }
```

And then in console:
- `FetchAuthenticatedUser`
- `finalize`
- `true` (from subscription on isLoading in component)

But in my case the issue is reproduced with low speed internet connection

**Comment by markwhitfeld** [comment] 2022-08-08 22:27
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:27 UTC
Labels: domain: plugins, domain: core, priority: high, type: bug/fix, released
