### ISSUE TITLE
🐞[BUG]: Initial state doesn't trigger in unit tests using overrideTemplate of TestBed

### ISSUE THREAD

**Issue by qannoufoualid** [ngxs/store#1882] opened 2022-07-24 13:39 UTC
### Affected Package
The issue is caused by package @ngxs/store 3.7.4

### Is this a regression?
Yes, the bug is not present in 3.7.3

### Description
Since the version 3.7.4 multiple unit tests of my project using overrideTemplate of TestBed are failing because the initial state doesn't trigger

## 🔬 Minimal Reproduction
I've made a simple project to reproduce https://github.com/qannoufoualid/ngxs-version-update
you can run unit tests on both versions 3.7.3 and 3.7.4 to see.

## Environment

<pre><code>
Libs:
- at least @angular/core version: 11.1.1
- @ngxs/store version:  3.7.4

**Comment by arturovt** [comment] 2022-07-24 19:57
Duplicate of #1854. See the comment: https://github.com/ngxs/store/issues/1854#issuecomment-1167955493.

**Closed by arturovt** 2022-07-24 19:57 UTC
