### ISSUE TITLE
📚[DOCS]: Setup on application root level 

### ISSUE THREAD

**Issue by Redaloukil** [ngxs/store#2105] opened 2024-03-09 23:31 UTC
### Description

I started playing a little bit with the library as a user for a project that I am working on.

With the introduction of standalone component since Angular 14.x.x, setting up Ngxs using `ngxsModule.forRoot()` on a standalone root AppComponent imports is no longer possible. here is a [link](https://stackoverflow.com/questions/74167935/how-to-use-ngxs-in-a-standalone-component ) describing a work around

### What's the affected URL?**
https://www.ngxs.io/getting-started/installation

### Expected vs Actual Behavior**

Additional hint about using appConfig providers on a standalone component  

```
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    importProvidersFrom(NgxsModule.forRoot([AppState])),
  ],
};
```

## 🔥 Exception or Error
Worth it also to discuss how to use forFeature on a standalone setup

**Comment by hakimio** [comment] 2024-03-10 23:09
[`provideStore()`](https://github.com/ngxs/store/blob/de99dad3fd0c33cc22deb32c5fd161f51969a956/publication/2023-09-30_announcing_ngxs_3_9/article.md#:~:text=provideStore(%0A%20%20%20%20%20%20%20%20%20%20%20%20%5BTodosState%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%20developmentMode%3A%20!environment.production%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20withNgxsReduxDevtoolsPlugin(%7B%20disabled%3A%20environment.production%20%7D)%0A%20%20%20%20%20%20%20%20)) will be released soon.

**Comment by arturovt** [comment] 2024-06-10 16:25
Great news! [v18.0.0](https://github.com/ngxs/store/releases/tag/v18.0.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the https://github.com/ngxs/store/discussions/2173 if you come across any regressions with respect to your issue.

**Closed by arturovt** 2024-06-10 16:25 UTC
