### ISSUE TITLE
🐞[BUG]: Async actions not running in lazy-loaded feature modules using webpack 5 module federation

### ISSUE THREAD

**Issue by matt-gold** [ngxs/store#1772] opened 2021-07-16 15:45 UTC
### Affected Package
@ngxs/store

### Description
Ngxs is not subscribing to observables returned from action handlers when the store is lazy-loaded via webpack 5's module federation. The specific module federation approach being used is: [@angular-architects/module-federation](https://github.com/angular-architects/module-federation-plugin/blob/main/libs/mf/README.md), and I have configured @ngxs/store to be shared in webpack.config.js. When the microfrontend is lazy loaded, I can see the .forFeature store being added to the shell apps store, and any actions that happen synchronously are able to update the state without issue. When I return observables from action handlers however, they do not run.

## 🔬 Minimal Reproduction
https://github.com/matt-gold/module-federation-plugin-example/tree/ngxs-issue
My reproduction takes a simplified version of the [baseline example](https://github.com/manfredsteyer/module-federation-plugin-example) project, adds a simple ngxs store to each app, and configures the @ngxs/store library to be shared in webpack.config.js. I have an h1 tag that reflects the state demonstrating that async actions are not working in the micro frontend when it is loaded with webpack5, but are working when the app is run standalone.
 
## Environment
Libs:
- @angular/core version: 12.1.2
- @ngxs/store version: 3.7.2
- @angular-architects/module-federation: 12.2.1

**Comment by arturovt** [comment] 2021-08-17 06:44
Hey @matt-gold 

I was able to debug your reproduction. It fails here:

https://github.com/ngxs/store/blob/bbf296871afe759eb35d2ab2b2c3cd2dd52b92d6/packages/store/src/internal/state-factory.ts#L245-L275

The `instanceof Observable` returns `false` (but it's an observable) and it bails out to the `else` block, which sets the observable to `of({})`. So it basically subscribes to the wrong observable and the `timer()` is not awaited to emit next and complete.

This means that apps and libraries are using different `Observable` classes. I'm not familiar with `module-federation`, but I'd definitely look for a way to share the `rxjs` package between everything.

I cannot say if it's possible to provide the UMD bundle inside the shell app, single-spa-angular has been fighting for sharing dependencies for many years.

**Comment by splincode** [comment] 2021-08-17 06:53
maybe need add  "rxjs": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },

![image](https://user-images.githubusercontent.com/12021443/129677628-f12d3de3-0d2d-49f1-ab69-5ddcd5739e64.png)

**Comment by matt-gold** [comment] 2021-08-18 19:58
Hi,
@splincode unfortunately I have already tried sharing rxjs as a singleton in this manner and it doesn't fix the issue. 
@arturovt Thanks for finding the source the problem! For some reason configuring rxjs as a singleton is not doing the trick, I'll need to investigate more from here... it seems this is not something that can be fixed within Ngxs.

**Comment by matt-gold** [comment] 2021-08-18 20:20
@splincode @arturovt 
Thanks for looking into this! 
I thought I had already tried sharing rxjs as a singleton, but apparently my configuration was wrong, because it is definitely working now! 

`"rxjs": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },`

This needs to be configured in the shell as well as each micro-frontend

**Comment by markwhitfeld** [comment] 2021-08-24 09:04
@matt-gold or @yybarham
Would either of you like to put together a guide on Module Federation for our docs?
It could be added to the [Recipes](https://www.ngxs.io/recipes) section of our docs: 
The code: https://github.com/ngxs/store/tree/master/docs/recipes

**Comment by adrian-goe** [comment] 2021-09-18 10:53
@markwhitfeld I added a  PR for the guide. https://github.com/ngxs/store/pull/1789

**Comment by markwhitfeld** [comment] 2021-09-22 08:43
@matt-gold and @yybarham I would love to get your thoughts/feedback/additions to the guide that @adrian-goe just added:
https://www.ngxs.io/v/master/recipes/module-federation
(it is only in the development docs at this time, will promote to main docs once I get your thoughts).

**Comment by arturovt** [comment] 2022-07-31 15:58
Closing as resolved since it wasn’t an NGXS bug initially. I’ve also noticed that module federation repo, that contains different examples with different frameworks, already has an example with NGXS.

**Closed by arturovt** 2022-07-31 15:58 UTC
