### ISSUE TITLE
🐞[BUG]: Select does not respect certain actions

### ISSUE THREAD

**Issue by kremerd** [ngxs/store#1976] opened 2023-03-15 16:06 UTC
### Affected Package

The issue is caused by package @ngxs/store. Affected versions are 3.7.5 and 3.7.6.

### Is this a regression?

Yes, the previous version in which this bug was not present was: 3.7.3.
In 3.7.4 the behavior was wrong in a different way. That was fixed in [!1880](https://github.com/ngxs/store/issues/1880).

### Description

1. `selectOnce` an arbitrary selector.
2. Dispatch an action that updates a state.
3. `selectOnce` the state.

**Expected behavior:** The result contains the update from the action.
**Action behavior:** The result _does not contain_ the update from the action.

#### Notes

* You can reproduce this behavior with `select` instead of `selectOnce`.
* You _cannot_ reproduce this behavior with `selectSnapshot`. It behaves correctly.
* Selecting something (`select` or `selectOnce`, not `selectSnapshot`) before dispatching the action is necessary for the bug to occur.

## 🔬 Minimal Reproduction

* [with Angular 8](https://stackblitz.com/edit/ngxs-repro-di6n1f)
* [with Angular 15](https://stackblitz.com/edit/ngxs-repro-pyun9q)

When you click on the button, a static selector is selected, then an action is dispatched that increases a counter. Finally the value of the counter is selected (a) with `selectSnapshot` and (b) with `selectOnce`. These values differ.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14, 14.2.12, 15.2.2
- @ngxs/store version: 3.7.5, 3.7.6

Browser:
- [x] Chrome (desktop) version 111.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 111.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by markwhitfeld** [comment] 2023-03-29 14:12
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:12 UTC
Labels: ready to release, domain: docs, type: bug/fix, released
