### ISSUE TITLE
Composition issue - extending State

### ISSUE THREAD

**Issue by piernik** [ngxs/store#193] opened 2018-03-29 09:28 UTC
### Versions

```
* ngxs: 2.0
* @angular/core: 5.2.6
```
I have one State that has configuration in it.
`ConfigState`

```
@State<ConfigStateModel>({
  name: 'config',
  defaults: {},
  children: [
    ConfigFirstModuleState
  ]
})
export class ConfigState {
}
```

All works great I have `config.firstModule` key in my store.

Now I lazyload a module that has another part of configuration - config for that `secondModule`.
Can I use `Composition` (https://ngxs.gitbooks.io/ngxs/advanced/composition.html) for that? 
If I extend `ConfigState` it attaches it to root state - not `config` branch:

```
@State<ConfigStateModel>({
  name: 'secondModule',
  defaults: {}
})
export class ConfigSecondModuleState extends ConfigState {
}
```

As result I have `root.config.firstModule` and `root.secondModule` instead of `root.config.firstModule` and `root.config.secondModule`.

**Comment by leon** [comment] 2018-04-01 14:29
I think it's smart to try to keep the state tree as shallow as possible.
If you have multiple config states, it doesn't matter if you get

```
state: {
  configOne: ...,
  configTwo: ...,
  ...,
  configFifty: ...
}
```

Don't use inheritance and nested states if you don't need them.
Think of every `@State` as a standalone thing that exists directly on the root, the same goes for feature states, the also exist directly on the root, they may or may not be lazy loaded.

So in your case I ask you, why do you need the parent ConfigState?

**Comment by piernik** [comment] 2018-04-03 07:41
@leon You're right - tree should be as shallow as possible but "readability" is also important.

1. I think of config as a `feature` module. This feature has it's own methods, services and so on. When I lazy load new module it has it's own config but I want it to be able to use methods, services and so on from `config` feature - also because that lazy loaded config can interfere with other module's config.

2. It will be clear that expanding some State You expand **that** state - not root one. It's logic.

**Comment by amcdnl** [comment] 2018-05-08 13:38
Closing as this is not a bug. Refer questions to stackoverflow.

**Closed by amcdnl** 2018-05-08 13:38 UTC
Labels: need feedback, question

**Comment by piernik** [comment] 2018-05-08 14:10
@amcdnl it is also feature request. Why You closed it?

**Comment by amcdnl** [comment] 2018-05-08 15:04
Sorry, I thought it was a question.

Re-reading I do NOT think it should extend the state. It would get REALLY confusing IMO.

**Comment by piernik** [comment] 2018-05-09 06:56
I think it's now confusing. You extend state and think that it will EXTEND that state not root one.
Please reconsider... I'll need it ;)

**Comment by dalu** [comment] 2018-11-29 22:13
If you have an auth state for instance, which should be "global", can you access this auth state in feature modules?
