### ISSUE TITLE
🐞[BUG]: state operator does not work withs classes defines getter setter

### ISSUE THREAD

**Issue by wunaidage** [ngxs/store#1673] opened 2020-09-19 19:30 UTC
### Description
if I design my state store like 
```
@State<SomeModel>({
  name: 'someModel',
  defaults: {
    aList: ABC[]
  }
})
```
and classes are defined like:
```
class ABC {
   private _id: string;
   private _data: any
  // getter setter
}
```
```
ctx.setState(
      patch(
        {
          aList: updateItem(item => item.id === passedIn, patch({data: somenewdata}))
        }
      )
    );
```
After I patch the state on data property. the element is unable to cast back to ABC and new property "data" is added.

**Comment by markwhitfeld** [comment] 2020-09-19 19:37
Hi there
It is not recommended to put class-based objects in your state.
See Style guide: https://www.ngxs.io/recipes/style-guide#avoid-saving-class-based-instances-in-your-state
A fundamental premise for state is that it is immutable, therefore the modifications applied by the state operators apply the copy-on-write technique in order to make a new copy with the modified data in it. Classes do not support this paradigm.

**Comment by markwhitfeld** [comment] 2020-09-19 19:38
Closing, because this is not a bug, but rather "by design".

**Closed by markwhitfeld** 2020-09-19 19:38 UTC

**Comment by wunaidage** [comment] 2020-09-19 19:51
thanks a lot Mark!
