### ISSUE TITLE
🐞[BUG]: Incorrect behavior when using @Selector

### ISSUE THREAD

**Issue by abalad** [ngxs/store#541] opened 2018-08-13 23:25 UTC
### Versions

```
* ngxs: 3.1.4
* @angular/core: 6.0.0
```

### Repro steps

Stackblitz / Github link: https://stackblitz.com/edit/ngxs-simple-selector-issue

* Create a @Selector that uses map to change some state value.
* Use this @selector with @Select in any component

### Observed behavior

```
Select is triggering changes to the Selector created with map even though it does not change the value it uses.
```
![image](https://user-images.githubusercontent.com/5459282/44063521-28febcd8-9f37-11e8-9dbc-ac704080de94.png)

### Desired behavior

The correct behavior would be that it does not fire the changes unless it is changed in the state the value that it is using

**Comment by markwhitfeld** [comment] 2018-08-14 11:54
Hi @abalad 
This is how memoization works. The returned value is cached based on the same input value.
In this case modifying the `counter` property results in a change to the container state which is then a new value passed to the `issueWithMap` selector which in turn results in a new calculated result.

You can get the behavior you are expecting by breaking down the `issueWithMap` selector's dependency to only be the `other` prop. This can be done using a composite selector but unfortunately (in ngxs v3) any composite selectors defined within the state class automatically take a dependency on the container class. So, to get this working you would need to move this selector to an unrelated class (this will be fixed in v4 and not necessary) so that it only takes a dependency on the provided selector.

Here is an example evolved from yours in a stackblitz:
https://stackblitz.com/edit/ngxs-simple-selector-issue-yrfhnp

**Comment by abalad** [comment] 2018-08-14 12:28
@markwhitfeld Thank you. What I was left in doubt is because the:

```
@Selector () static others (state: CounterStateModel) {
     return state.other;
}
```
Does not issue changes even though I change the `state.counter`. 
Already when I realize a `map() `in him it is shot. 

That's what I do not understand.

**Comment by markwhitfeld** [comment] 2018-08-14 13:10
The `others` selector re-evaluates when the state changes but because it returns the same value as before the subscription does not fire. The observable has a `distinctUntilChanged` operator on it so the same returned value is ignored.

The `Object.keys(...)` call is returning a new value whenever the selector is re-evaluated which gets through the `distinctUntilChanged`. This is why it is different to the `others` selector.

Hope this answers all your questions ;-)

**Comment by abalad** [comment] 2018-08-14 13:25
@markwhitfeld Thank you so much. Now I understand.

**Comment by abalad** [comment] 2018-08-14 13:37
To finalize the solution then final.

I've split my selectors into 2 files. One with the basic properties and the other file with all the selectors that the application will use.

`usuario.state.ts`
```typescript
@State<UsuarioStateModel>({
  name: 'usuario',
  defaults: EntityStateModel.InitialState()
})
export class UsuarioState implements NgxsOnInit {

  @Selector()
  static selected(state: UsuarioStateModel) {
    return state.selected;
  }

  @Selector()
  static entities(state: UsuarioStateModel) {
    return state.entities;
  }
.
.
.
```
`usuario.selectors.ts`
```typescript 
export class UsuarioSelectors {
  @Selector([UsuarioState.entities])
  static entities(entities: UsuarioStateModel['entities']) {
    return new EntitySelector().getEntities( entities );
  }

  @Selector([UsuarioState.selected])
  static selected(selected: UsuarioStateModel['selected']) {
    return selected;
  }
}
```
`usuario.sandbox.ts`
```typescript
@Injectable()
export class UsuarioSandbox {

  @Select( UsuarioSelectors.selected ) usuarioSelected$: Observable<Usuario>;

  @Select( UsuarioSelectors.entities ) usuariosCollection$: Observable<Usuario[]>;

  constructor( private store: Store ) {}
.
.
.
```

**Comment by arturovt** [comment] 2022-08-10 07:59
Seems like this is stalled and was answered long time ago, so closing as not a bug.

**Closed by arturovt** 2022-08-10 07:59 UTC
Labels: domain: docs
