### ISSUE TITLE
🚀[FEATURE]: Support Angular 18

### ISSUE THREAD

**Issue by JimLixin** [ngxs/store#2167] opened 2024-05-23 08:27 UTC
### Relevant Package
All Ngxs packages.

### Description
Support Angular 18.

### Describe the problem you are trying to solve
Trying to update our codebase to Angular 18.

### Describe the solution you'd like
Relax the restriction in `package.json`.

### Describe alternatives you've considered
None at this time.

![image](https://github.com/ngxs/store/assets/21256507/52dad36d-f8e9-4c6d-baea-1213663deb32)

**Comment by mrs-cp** [comment] 2024-05-24 13:11
yes, angular 18 support would be great, thanks! 👍

**Comment by JGSolutions** [comment] 2024-05-24 22:38
would be great

**Comment by idrayv** [comment] 2024-05-26 17:47
Thanks, waiting for that so much ;)

**Comment by mountpoint** [comment] 2024-05-31 14:03
Waiting for Angular 18 support =)

**Comment by AliElba** [comment] 2024-06-02 14:56
Waiting for Angular 18 support very hard :)

**Comment by siddharthcn21** [comment] 2024-06-05 09:18
by when we can expect angular 18 support?

**Comment by markwhitfeld** [comment] 2024-06-05 13:01
Hi everyone
We hope to cut the next release very soon, but it is a huge release so there are a few things to coordinate first.
You can use the `@dev` version of the packages right now to use the release candidate with Angular 18 support in your projects.

**Comment by JGSolutions** [comment] 2024-06-05 13:22
Thx @markwhitfeld for the update :)

**Comment by markwhitfeld** [comment] 2024-06-07 10:57
@hakimio Thanks for pointing that out. 
I think it is in error. The minimum version should be v16.

**Comment by arturovt** [comment] 2024-06-10 16:12
Great news! [v18.0.0](https://github.com/ngxs/store/releases/tag/v18.0.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the https://github.com/ngxs/store/discussions/2173 if you come across any regressions with respect to your issue.

**Closed by arturovt** 2024-06-10 16:12 UTC
Labels: domain: plugins, domain: core, priority: critical, type: build, state: has PR

**Comment by hakimio** [comment] 2024-06-10 16:19
@arturovt where is upgrade guide like [this one](https://github.com/ngxs/store/blob/de99dad3fd0c33cc22deb32c5fd161f51969a956/publication/2023-09-30_announcing_ngxs_3_9/article.md)?

**Comment by markwhitfeld** [comment] 2024-06-10 18:47
PS. We are releasing v18 now as a "soft launch" while we work on making sure that the release announcement that you found above is ready to go.
If you spot anything that is unclear in that announcement, we welcome any feedback. 🙏

**Comment by hakimio** [comment] 2024-06-10 19:30
Looks good as far as I can see.
Also, really love the new `select()` and `createSelectMap()` signal utility functions. No need for `*ngrxLet` and `combineLatest()` anymore 🙂
