### ISSUE TITLE
🐞[BUG]: Cyclic next detected

### ISSUE THREAD

**Issue by Areen3** [ngxs/store#1516] opened 2020-01-19 14:47 UTC
### Affected Package
 The issue is caused by package @ngxs/store version 3.6.1

### Is this a regression?
 I think it is present
### Description

I found this error/warning, when I write a factory simulation showing new functions that I added to ngxs (in a few days I will post the issue)

Factory simulation slows me down during work and to see what problem I started using rxjs_spy.
the problem is with the return from calling the action when it returns the observed result
simply: 
 this.store.dispatch(new fromModel.CompanyMenagmentAction.Pause(0)); <-- without warnig
return this.store.dispatch(new fromModel.CompanyMenagmentAction.Pause(0)); <--with warning

## 🔬 Minimal Reproduction
here is project
https://github.com/Areen3/ngxs-circular
in file firm.state.ts You have method updateFinance
You can comment and remove comment to see warning:
Cyclic next detected; type = internalDispatchedActionResults; value = [object Object]; subscribed at
FilterOperator.call (http://localhost:4200/vendor.js:113050:23)
AnonymousSubject.subscribe (http://localhost:4200/vendor.js:108265:31)
http://localhost:4200/vendor.js:107614:48
notify_ (http://localhost:4200/vendor.js:107508:13)

You can see these warning on console
but ngxs works good, acton was send and working.

**Comment by arturovt** [comment] 2020-06-21 00:25
From what I see in your reproduction your code is actually valid. You handle the first action and then you `return dispatch(anotherAction)` which is a valid NGXS code and it's designed to handle this case.

If it's bothering you then just disable it:
```ts
import { create } from 'rxjs-spy';
import { CyclePlugin } from 'rxjs-spy/plugin';

export class AppModule {
  constructor() {
    const spy = create();
    spy.unplug(spy.find(CyclePlugin));
  }
}
```

I'm closing this issue because it's not an NGXS issue.

**Closed by arturovt** 2020-06-21 00:25 UTC
