### ISSUE TITLE
🐞[BUG]: Can't use isolatedModules with NGXS

### ISSUE THREAD

**Issue by ablomq** [ngxs/store#2212] opened 2024-08-23 15:09 UTC
### Affected Package
@ngxs/store 18.1.1

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

When enabling the following typescript compile options:
```
        "isolatedModules": true,
        "useDefineForClassFields": true,
```

More info about these settings: [Using isolatedModules in Angular 18.2](https://blog.angular.dev/using-isolatedmodules-in-angular-18-2-68a7d3a6c03d)

I then get this error: *ERROR] TS1272: A type referenced in a decorated signature must be imported with 'import type' or a namespace import when 'isolatedModules' and 'emitDecoratorMetadata' are enabled. [plugin angular-compiler]*

I can't import `StateContext` in my states without using either:

`import type { StateContext } from '@ngxs/store';`

or

`import Ngxs from '@ngxs/store`

But when using these imports I get a runtime exception like this when using i.e. setState, getState etc.

`TypeError: Cannot read properties of undefined (reading 'pipe')`

```
            this.store
                .dispatch(new User.Get())
                .pipe(
                    mergeMap(() =>
                        this.languageService.setLanguage().pipe(
```
## 🔥 Exception or Error
`TypeError: Cannot read properties of undefined (reading 'pipe')`

## Environment

<pre><code>
Libs:
- @angular/core version: 18.2.1
- @ngxs/store version: 18.1.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 20.15.1  
- Platform:  Mac

Others:

</code></pre>

**Comment by markwhitfeld** [comment] 2024-08-23 21:32
@ablomq I tried to reproduce the issue in a StackBlitz project, but it works fine. See here:
https://stackblitz.com/edit/tptxd8-tyr7u1?file=tsconfig.json,src%2Fapp%2Fcookie%2Fcookie.state.ts

Please could you create a StackBlitz reproduction for this issue.

**Comment by ablomq** [comment] 2024-08-27 15:33
I suspect the issue happens when using the `@Select` decorator. I tried to add that to the example you provided but the project doesn't run. Anyway here is the StackBlitz link: [https://stackblitz.com/edit/tptxd8-yv6xwx?file=src%2Fmain.ts](https://stackblitz.com/edit/tptxd8-yv6xwx?file=src%2Fmain.ts)

**Comment by arturovt** [comment] 2024-10-20 22:58
Closing because it's not reproducible.

**Closed by arturovt** 2024-10-20 22:58 UTC
