### ISSUE TITLE
Inconsistent Select() behavior when using string and function expressions

### ISSUE THREAD

**Issue by ogix** [ngxs/store#1109] opened 2019-05-31 07:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using function expression in Select to take a deeper slice of state, the observable will not be triggered.
e.g. ` @Select(s => s.app.settings.userSettings) userSettings$: Observable<any>;` and then in `ngOnInit: this.userSettings$.subscribe(res => console.log(res)); // not triggered`

When using string expression in Select to take a deeper slice of state, the observable will be triggered.
e.g. ` @Select('app.settings.userSettings') userSettings$: Observable<any>;` and then in `ngOnInit: this.userSettings$.subscribe(res => console.log(res)); // triggered`

## Expected behavior

I expect Select observable to be triggered in both cases.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.0.0
- @ngxs/store version: 3.4.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment] 2019-05-31 07:38
create stackblitz example please

**Comment by arturovt** [comment] 2019-07-22 13:42
Closing this issue as not reproducable. I checked your example with sub states and it works for me. Will re-open if I see a reproduction :wink: And also please create stackblitz examples, as I don't want to run through the instructions in the "current behavior" to try to to reproduce error.

**Closed by arturovt** 2019-07-22 13:42 UTC
