### ISSUE TITLE
🐞[BUG]: Infinite Action Dispatching Cycle

### ISSUE THREAD

**Issue by adityaingle2** [ngxs/store#1822] opened 2022-02-04 20:29 UTC
### Affected Package

@ngxs/form-plugin: 3.7.3

### Description

When using the ngxs/form-plugin, some or multiple conditions cause the application to dispatch the "Update Form Value" , "Update Form Dirty", and "Update Form Errors" in an infinite loop, ultimately causing the application to crash. 

## 🔬 Minimal Reproduction

The simplest way to repro this issue is to have two forms on the same component bound to the same "ngxsForm" directive. (Essentially, we can follow the example for the ngxs forms plugin on the official website, and simply create a second copy of the form in the component). The snippets below shows a simpler example of this:

the code in app.component.html:
![appcomponenthtml](https://user-images.githubusercontent.com/13954083/152598483-275e35a8-c8f4-4ea2-aa71-c81bea85288f.png)

the code in app.component.ts:
![appcomponentts](https://user-images.githubusercontent.com/13954083/152598668-974255aa-9764-4661-8cc4-96cad9504fe7.png)

## 🔥 Exception or Error

After simply launching the application, the following can be observed when looking at the ReduxDevTools (the number of actions dispatched does not stop at the number in the red box - it continues endlessly until the application crashes): 

![ngxsFormLoop](https://user-images.githubusercontent.com/13954083/152596713-b6898083-985c-44dd-b1a2-a23be4848b7f.png)

## Environment

We ran into the same behavior (i.e. the infinite action dispatching loop) in our production app, which is more complex; however, the circumstance in which it occurred there is not identical to this (we did not have two distinct forms bound to the same ngxsForm directive); however, the example above was the simplest way to reproduce that behavior. 

With that, it's difficult to pinpoint if there are multiple conditions that can cause this infinite action dispatching loop, or if all instances of this behavior can be attributed to a single common condition. 

Libs:
- @angular/core version: 13.2.0
- @ngxs/store version: 3.7.3

Browser:
- [ ] Chrome (desktop) version 97

Others:
@ngxs/devtools-plugin: 3.7.3

**Comment by markwhitfeld** [comment] 2022-03-06 20:03
@adityaingle2 Thanks for the report. It was never the intention of this plugin that the same state would be bound twice, but, given your example, there could be an improvement to guard against the infinite loop.
The issue there is that Reactive Forms always returns a new object on any update, even if the property values haven't changed. This causes another update from the state because the objects aren't `===` (even though they have equal props).

One thing that could be done is that when the form value changes, it could be compared to the current value in state for that form using deep value equality and only if it has changed, then the `UpdateFormValue` would be dispatched (see the `updateFormStateWithRawValue` method).

On the other hand, I think it is a bit tricky to be binding 2 `ngForm`s to the same form state. It makes it a bit tricky in terms of what the `dirty`, `status` and `errors` properties represent. I can't wrap my head around what a reasonable expectation of these form state status type properties would be.
I usually recommend just having 2 separate form states and synchronise them outside the plugin if necessary. The data from the multiple form state can be composed using selectors too.

**Comment by markwhitfeld** [comment] 2022-08-08 22:27
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:27 UTC
Labels: domain: plugins, domain: core, priority: medium, type: bug/fix, released
