### ISSUE TITLE
Type safe @Select

### ISSUE THREAD

**Issue by lppedd** [ngxs/store#1026] opened 2019-04-29 09:17 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
Class' variables annotated with the `@Select` decorator, e.g.
```
@Select(EntityState.entity)
entity$: Observable<Entity>;
```
Aren't type safe. That means I can write 
```
@Select(EntityState.entity)
entity$: Observable<string>;
```
and still compile without errors.

## Expected behavior
Would be cool to have a compilation error when the type doesn't match with the selector's return type.

## What is the motivation / use case for changing the behavior?
Better type safety.

<pre><code>Libs:
- @angular/core version: 7.2.14
- @ngxs/store version: 3.4.3
</code></pre>

**Comment by lppedd** [comment] 2019-04-29 09:19
This is very similar to https://github.com/ngxs/store/issues/160, so it might be a duplicate.

**Comment by arturovt** [comment] 2019-05-05 16:48
@lppedd 

Decorators are not type safe regaring decorated members. But selectors are:

```ts
entity$: Observable<string> = this.store.select(EntityState.entity) // error
```

**Comment by arturovt** [comment] 2019-05-07 12:38
Closing this as a duplicate of #160.

**Closed by arturovt** 2019-05-07 12:38 UTC
