### ISSUE TITLE
🐞[BUG]: Old value emitted in new select after a reset if a select occurred prior to the reset

### ISSUE THREAD

**Issue by SLKnutson** [ngxs/store#1880] opened 2022-07-18 20:43 UTC
### Affected Package
@ngxs/store

### Is this a regression?
Yes, worked correctly prior to version 3.7.4

### Description
Old value emitted in new select after a reset if a select has already occurred

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ngxs-repro-mth3x9?file=src/app/app.component.ts

Look at the console. The first select value should match the snapshot (100), instead it initially shows the old value (3), and then goes to the new value (100)

## Environment

Libs:
- @ngxs/store version: 3.7.4

node & browser
 
 
 ## Thanks!

**Comment by markwhitfeld** [comment] 2022-08-08 22:24
Great news! [v3.7.5](https://github.com/ngxs/store/releases/tag/v3.7.5) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.7.5 release discussion](https://github.com/ngxs/store/discussions/1909) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2022-08-08 22:24 UTC
Labels: domain: core, priority: high, type: bug/fix, released
