### ISSUE TITLE
🐞[BUG]: State Selectors emit at navigation but before OnDestroy

### ISSUE THREAD

**Issue by BenRacicot** [ngxs/store#1836] opened 2022-04-20 12:35 UTC
Hello! I have refactored my app's auth and user state setups to track a bug where all selectors of my UserState emits upon navigating away from the component (but before its `OnDestroy`) despite state remaining unchanged. 

This makes no sense and is perhaps a side-effect of something unrelated.

Here is the [StackOverflow ](https://stackoverflow.com/questions/71930248/ngxs-global-states-slices-emit-on-every-navigation)question.

Here is the chronological order of events in the app

1. OnInit
2. slice emits -> fetch with params <-- EXPECTED
3. user clicks to navigate to a new page
4. slice emits -> fetch with params <-- UNEXPECTED EMIT
5. OnDestroy

I'm hoping someone from the team or community can help me understand what would cause all the Selectors in a state to emit when it has not been updated (no actions triggered) and why it would this specifically be triggered by Angular's navigation.

Here is the State log confirming that user state (and thus my Selector) are not being updated from the resting Calendar page to the next page's `@@UPDATE_STATE`

<img width="1378" alt="navigation-cal-to-snap" src="https://user-images.githubusercontent.com/1815385/164090300-347eabcf-186a-470d-83cb-6b6f94fe403a.png">

## 🔬 Minimal Reproduction
I cannot get this issue to repro. Tried with [this stackblitz](https://stackblitz.com/edit/angular-ngxs-template-y2ekx4?file=src%2Fapp%2Ftodo.state.ts). It at least demonstrates that as you navigate away from page two we should not be expecting selectors to fire on navigation (and before page two's OnDestroy)

The state does not change! 
`ngxsOnChanges(change: NgxsSimpleChange) { ...` only happens on init. It is never triggered in this flow despite the selectors emitting unchanged data on navigation.

**Comment by arturovt** [comment] 2022-08-10 08:04
Hey, I've just looked at your reproducible example. I was looking at console logs and was going between pages. Honestly saying, I didn't understand what means "selectors emit at navigation". I only see you're adding todo in the page-two, which, of course, triggers selector recalculation. I'll close this as not a bug until the reproducible example is provided.

**Closed by arturovt** 2022-08-10 08:04 UTC
