### ISSUE TITLE
application storage doesn't persist if the setState function runs in an Observable's finalize function.

### ISSUE THREAD

**Issue by lorentzyip** [ngxs/store#506] opened 2018-07-17 12:03 UTC
### Versions

```
* ngxs: 3.2.0
* @angular/core: ^6.0.3
```

### Repro steps

Stackblitz / Github link: https://stackblitz.com/edit/ngxs-simple-e5qvc2

* app.state.ts

```
import { State, Action } from '@ngxs/store';
import { AppService } from './app.service';
import { finalize, tap } from 'rxjs/operators';

export class Add {
  static readonly type = 'Add';
}

export class Reset {
  static readonly type = 'Reset';
}

@State<number>({
  name: 'count',
  defaults: 0
})
export class CountState {
  constructor(private appService: AppService) {}

  @Action(Add)
  add({ getState, setState }) {
    const state = getState();
    setState(state + 1);
  }

  @Action(Reset)
  reset({ getState, setState}) {
    return this.appService.delay()
      .pipe(
        // tap(() => setState(0)),
        finalize(() => setState(0))
      );
  }
}
```

* app.service.ts

```
import { Injectable } from '@angular/core';
import { timer } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AppService {

  constructor() { }

  delay() {
    return timer(1000);
  }
}
```

* app.component.ts

```
import { Component } from '@angular/core';
import { Store, Select } from '@ngxs/store';
import { Observable } from 'rxjs';
import { Add, Reset, CountState } from './app.state';

@Component({
  selector: 'my-app',
  template: `
    <h1>Count is {{count$ | async}}</h1>
    <button (click)="add()">Add</button>
    <button (click)="reset()">Reset</button>
  `
})
export class AppComponent  {

  @Select(CountState) count$: Observable<number>;

  constructor(private store: Store) {}

  add() {
    this.store.dispatch(new Add());
  }

  reset() {
    this.store.dispatch(new Reset());
  } 
}
```

* app.module.ts

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgxsModule } from '@ngxs/store';
import { NgxsStoragePluginModule } from '@ngxs/storage-plugin';

import { AppComponent } from './app.component';
import { CountState } from './app.state';

@NgModule({
  imports: [
    BrowserModule,
    NgxsModule.forRoot([CountState]),
    NgxsStoragePluginModule.forRoot({ key: ['count'] })
  ],
  declarations: [
    AppComponent
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
```

### Observed behavior

Click add button few times to increase `count`, say `2` and then press reset. The `count` number is correctly reset to `0`. However, when opening the chrome's dev tools, the application local storage still show the count to be `2` such that if the page is refreshed, the `count` will be restored to `2`.

However, if the `setState` function is called in `tap`:
```
@Action(Reset)
  reset({ getState, setState}) {
    return this.appService.delay()
      .pipe(
        tap(() => setState(0)),
        //finalize(() => setState(0))
      );
  }
```
It becomes normal and works as expected.

### Desired behavior

I expect that no matter I put the `setState` in `tap` or `finalize`, the state will be correctly persisted in Local Storage. The reason I prefer to put it in `finalize` because I want to implement a logout function such that no matter the observable returns success or error, the `setState` will always be called.

**Comment by Karolis92** [comment] 2018-12-04 14:33
Same hare, `initialized` doesn't get set to `true` here:
```
import { Action, NgxsOnInit, State, StateContext } from '@ngxs/store';
import { CheckSession, LoginFailed, LoginSuccess } from './auth.actions';
import { UserDataService } from '../services/user-data/user-data.service';
import { AuthStateModel } from './auth.model';
import { catchError, finalize, flatMap } from 'rxjs/operators';
import { Observable } from 'rxjs';

@State<AuthStateModel>({
  name: 'auth',
  defaults: {
    initialized: false
  }
})
export class AuthState implements NgxsOnInit {

  constructor(private userDataService: UserDataService) {}

  ngxsOnInit(ctx: StateContext<AuthStateModel>): void {
    ctx.dispatch(new CheckSession());
  }

  /*
   * Commands
   */
  @Action(CheckSession)
  checkSession(ctx: StateContext<AuthStateModel>): Observable<void> {
    return this.userDataService.getUserData().pipe(
      finalize(() => {
        ctx.patchState({initialized: true});
      }),
      flatMap(user => {
        return ctx.dispatch(new LoginSuccess(user));
      }),
      catchError(error => ctx.dispatch(new LoginFailed(error.status)))
    );
  }

  /*
   * Events
   */

  @Action(LoginSuccess)
  loginSuccess(ctx: StateContext<AuthStateModel>, action: LoginSuccess): void {
    ctx.patchState({
      user: action.payload,
      error: undefined
    });
  }

  @Action(LoginFailed)
  loginFailed(ctx: StateContext<AuthStateModel>, action: LoginFailed): void {
    ctx.patchState({
      user: undefined,
      error: action.payload
    });
  }
}
```

**Comment by arturovt** [comment] 2019-05-25 21:38
@lorentzyip @Karolis92 

This is a normal behavior because `finalize` invokes the callback when the stream completes or errors.

The issue is that the callback passed into `finalize` operator is invoked after the new state is setted, we can't track it. `setState` is a simple function where you provide the new state and we set this state globally, `setState` is syncrhonous.

When you dispatch an action - NGXS receives this action, then looks for the handler by `static type` property, creates a temporary `StateContext`, invokes handler method with `StateContext` and `action instance` arguments.

In this example
```TS
return timer(1000).pipe(
  finalize(() => setState(0))
);
```

The `finalize` callback will be invoked AFTER NGXS performs all internal operations:
```TS
import { timer } from 'rxjs';
import { finalize } from 'rxjs/operators';

const timer$ = timer(1000).pipe(
  finalize(() => console.log('3'))
);

timer$.subscribe({
  next: () => console.log('1'), // here NGXS does all internal stuff
  complete: () => console.log('2')
});
```

I understand your point of using `finalize` and that it requires some code duplication:
```TS
@Action(LoadCountries)
loadCountries(ctx) {
  ctx.patchState({ isLoading: false });

  return this.countriesService.loadCountries().pipe(
    catchError((error) => {
      ctx.patchState({ isLoading: false });
      return throwError(error);
    }),
    tap(() => ctx.patchState({ isLoading: false }))
  );
}
```

Finally you can do in a more declarative way:
```TS
function showLoader(ctx) {
  ctx.patchState({
    isLoading: true
  });
}

function hideLoader(ctx) {
  ctx.patchState({
    isLoading: false
  });
}

loadCountries(ctx) {
  showLoader(ctx);

  return this.countriesService.loadCountries().pipe(
    catchError((error) => {
      hideLoader(ctx);
      return throwError(error);
    }),
    tap(() => hideLoader(ctx))
  );
}
```

**Closed by arturovt** 2019-05-25 21:38 UTC
Labels: domain:core

**Comment by martinsotirov** [comment] 2020-06-22 11:34
I was facing the same problem with patching state within a subscribe callback and `toPromise()` was the solution. I'm much more comfortable with Promises than with Observables anyway.
