### ISSUE TITLE
🐞[BUG]: Regression - Router plugin behavior change in 3.7.0

### ISSUE THREAD

**Issue by catchshyam** [ngxs/store#1718] opened 2021-01-11 16:37 UTC
### Affected Package
@ngxs/router-plugin

### Is this a regression?
Yes

### Description
The target URL and params are not reflected in the RouterState.state during routing (for example when accessed in the route guards and resolvers)

## 🔬 Minimal Reproduction

Angular 8 with ngxs store and router plugin 3.3.1
https://stackblitz.com/edit/angular8-ngxs-issue-1605

Angular 10 with ngxs store and router plugin 3.7.0
https://stackblitz.com/edit/angular10-ngxs-issue-1605

On the /home route, click on "details" link.

And on the details page, you will see the detected URL. With angular 8, the url is "details" while aith angular 10, it is displayed as home.

## Environment

<pre><code>
Libs:
- @angular/core version: 10.2.1
- @ngxs/store version: 3.7.0

Browser:
- [x ] Chrome (desktop) version 86.0.4240.198
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ x] Edge version XX

**Comment by markwhitfeld** [comment] 2023-03-29 14:08
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:08 UTC
Labels: domain: plugins, ready to release, type: bug/fix, released
