### ISSUE TITLE
🐞[BUG]: 'Error: NG0205: Injector has already been destroyed.' after upgrading to 3.7.4

### ISSUE THREAD

**Issue by GabrielAPineiro** [ngxs/store#1869] opened 2022-06-22 09:18 UTC
Affected Package
The issue is caused by package @ngxs/3.7.4

Is this a regression?
Yes, the previous version in which this bug was not present was: 3.7.3

Description
After upgrading to 3.7.4 our CI pipeline started to fail on tests with this error

🔬 Minimal Reproduction
The failing test is inside a service, which is using some list of menuItems in a observable. The component that uses the service extends a Unsubscribe class, which implements ngOnDestroy 

Minimally reproducible example:

![image](https://user-images.githubusercontent.com/104081429/174992862-ea1f358d-a2f7-400e-b2c8-beb7cf200ea5.png)

![image](https://user-images.githubusercontent.com/104081429/174990491-8b3a80d0-48dd-45bc-bd3a-72fd3eedaa42.png)

![image](https://user-images.githubusercontent.com/104081429/174990549-01912eb7-745f-4d4b-a3b6-bbafcc3e82cd.png)

![image](https://user-images.githubusercontent.com/104081429/175251877-43705835-cd50-4848-9b95-309d4500c36f.png)

![image](https://user-images.githubusercontent.com/104081429/174990581-bf4033ab-bae2-4c4f-89f6-1e07f95a091a.png)

🔥 Exception or Error

Error: NG0205: Injector has already been destroyed.
	error properties: Object({ code: 205 })
	Error: NG0205: Injector has already been destroyed.
	    at R3Injector.assertNotDestroyed (node_modules/@angular/core/fesm2015/core.mjs:11360:1)
	    at R3Injector.get (node_modules/@angular/core/fesm2015/core.mjs:11288:1)
	    at localInject (node_modules/@ngxs/store/fesm2015/ngxs-store-internals.js:279:1)
	    at node_modules/@ngxs/store/fesm2015/ngxs-store.js:3931:54
	    at doInnerSub (node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:19:18)
	    at outerNext (node_modules/rxjs/dist/esm/internal/operators/mergeInternals.js:14:1)
	    at OperatorSubscriber._next (node_modules/rxjs/dist/esm/internal/operators/OperatorSubscriber.js:9:1)
	    at OperatorSubscriber.next (node_modules/rxjs/dist/esm/internal/Subscriber.js:31:1)
	    at ReplaySubject._subscribe (node_modules/rxjs/dist/esm/internal/ReplaySubject.js:31:1)
	    at ReplaySubject._trySubscribe (node_modules/rxjs/dist/esm/internal/Observable.js:37:1)

Environment

Libs:
- @angular/core version: 13.3.11
- @ngxs/store version: 3.7.4 (when breaking)

Browser:
- Chrome Headless 102.0.5005.115 (Linux x86_64)
-  
For Tooling issues:
- Node version:  Node 16.15.1
- Platform:  Linux, Ubuntu

Others:

Downgrading from 3.7.4 to 3.7.3 resolved the issue

**Comment by arturovt** [comment] 2022-06-22 10:29
I'm not sure I can tell anything from screenshots.

**Comment by arturovt** [comment] 2022-07-30 12:46
Closing as duplicate of #1854

**Closed by arturovt** 2022-07-30 12:46 UTC
