### ISSUE TITLE
🚀[FEATURE]: Provide state slices as selectors out-of-the-box

### ISSUE THREAD

**Issue by Carniatto** [ngxs/store#1653] opened 2020-08-06 11:47 UTC
### Relevant Package

This feature request is for @ngxs/store

### Description
Provide state slices as selectors out-of-the-box

### Describe the problem you are trying to solve
 Please describe the problem. If possible please substantiate it with the use cases you want to address.
When working with `ngxs` selectors is common t have basic selectors just to slice the basic properties of your state like shown below:

```ts
export class TodoStateQueries {
  @Selector([TodoState])
  static selected(state: TodoStateModel) {
    return state.selected;
  }

  @Selector([TodoState])
  static todos(state: TodoStateModel) {
    return state.todos;
  }
}
```
This can become a tedious process. There is a possibility to improve this using `dynamic selectors`:

```ts
export class TodoStateQueries {
  static getSlice(property: keyof TodoStateModel) {
    return createSelector([TodoState], (state: TodoStateModel) => state[property]);
  }

  // usage
  @Selector([TodoStateQueries.getSlice('selected'), TodoStateQueries.getSlice('todos')])
  static getSelectedTodoos...

}
```
This is a better approach but been a very common use case would be nice to have something like this out-of-the-box.

### Describe the solution you'd like
A possible solution would be to provide a function `createPropertySelectors` that would split the state in selectors or each property like shown below:

```ts
export const TodoStateProps = createPropertySelectors<TodoStateModel>(TodoState)

@Selector([TodoStateProps.selectedIds, TodoStateProps.todos)])
static getSelectedTodos....
```

### Describe alternatives you've considered
There are other alternatives provided by @poloagustin and @joaqcid respectivly

``` ts
import {getStateSlice} from '@ngxs/store'

@Selector([getStateSlice(AppState, 'users')])
static getUsers....
```

**Comment by joaqcid** [comment] 2020-08-06 12:13
last solution can also be

```
const CounterStateProps = createPropertySelector<CounterStateModel>(CounterState);

@Selector([CounterStateProps('count'), CounterStateProps('loaded')]) static combined(
    count: number,
    loaded: boolean
  ) {
    return loaded && count;
  }
```

**Comment by armanozak** [comment] 2020-08-07 15:57
Hi @Carniatto, @joaqcid,

Take a look at [this playground](https://stackblitz.com/edit/ngxs-state-slice?file=src/app/app.state.ts). When every state has its own slicer, you no longer have a slicing problem. ;)

Have a cheerful day.

**Comment by joaqcid** [comment] 2020-08-07 16:05
that's another interesting way of doing it, we thought of using `keyof` to select the property to slice

**Comment by armanozak** [comment] 2020-08-07 17:15
I prefer functions, because they are more flexible and reusable. That doesn't mean keys can't be used. I'd rather not have an overloaded function though. Please consider introducing separate functions, if you decide having both.

**Comment by Carniatto** [comment] 2020-08-09 18:57
I think the function defeats the purpose of making it more readable, but maybe we can consider accepting both?

**Comment by splincode** [comment] 2020-08-11 11:37
@markwhitfeld @Carniatto what do you think about:

```
import { sliceByState } from '@ngxs/store/utils';

 @Selector([ sliceByState({ state: AppState, path: 'users' }) ])
static getUsers....
```

**Comment by joaqcid** [comment] 2020-08-11 12:31
i think the only i like the most is this one

```
export const TodoStateProps = createPropertySelectors<TodoStateModel>(TodoState)

@Selector([TodoStateProps.selectedIds, TodoStateProps.todos)])
static getSelectedTodos....
```

**Comment by irowbin** [comment] 2020-09-03 08:12
Similarly I've used dynamic properties to select correct  slice of state where decorators are not allowed.


```ts

interface AppStateModel{
  state1: number
  state2: string
}

export class AppStateSelectors {

static sliceOf<K extends keyof AppStateModel>(stateKey: K, args?: any) {
    return createSelector([AppState], (state: AppStateModel) => {

      return state[stateKey] as AppStateModel[K] // by doing so, we can have its type when selecting.

    })

}

// to use
stuffsToDo(){
this.store.select(AppStateSelectors .sliceOf('state1')) // returns correct type as  number
this.store.select(AppStateSelectors .sliceOf('state2')) // returns correct type as  string
this.store.select(AppStateSelectors .sliceOf('state100')) // oops, error, key not found

// other stuffs 
}
```

**Comment by rbudnar** [comment] 2020-09-14 14:20
I  came up with a similar solution as mentioned in https://github.com/ngxs/store/issues/1653#issuecomment-686330778:
```
export const createPropsSelector = <TStateModel, K extends keyof TStateModel>(
    stateToken: StateToken<TStateModel>,
    ...keys: K[]
) => {
    const selectors = keys.map(key => createSelector([stateToken], (state: TStateModel) => state[key]));
    return createSelector([...selectors], (...selected) => {
        return keys.reduce((acc, key, i) => {
            acc[key] = selected[i];
            return acc;
        }, {} as Pick<TStateModel, K>);
    });
};
```
To be used like:
```
// state token for app state:
export const APP_SETTINGS_STATE_TOKEN = new StateToken<AppSettings>("appsettings");

//
this.store.select(createPropsSelector(APP_SETTINGS_STATE_TOKEN, "prop1", "prop2", "prop3"))
```
It's a bit more generic and requires a state token but you do get strong typing and intellisense down stream.

**Comment by Carniatto** [comment] 2020-09-29 07:54
I've created this Gist with the initial proposal for this feature. 
https://gist.github.com/Carniatto/0e677ec9b43f949c07538e4c69e1f9ce

Please try it out. We are looking for feedback to refine this before integrating out of the box

**Comment by markwhitfeld** [comment] 2020-10-01 11:38
@Carniatto Could you improve your `createPickSelector` in your gist and the comment above with the function from @rbudnar https://github.com/ngxs/store/issues/1653#issuecomment-692084882 
Just change the name to `createPickSelector`.
PS. Do you think the second argument of this function should rather be an array as opposed to a spread array? I think it leaves room for the function signature to grow if it needs to one day.

**Comment by rbudnar** [comment] 2020-10-01 11:47
@markwhitfeld That seems like a reasonable update and would reduce chances of breaking changes in the future if the signature does need to change :+1:

**Comment by Carniatto** [comment] 2020-10-07 08:52
@markwhitfeld @rbudnar  I've updated the Gist and the comment to match your suggestions.

**Comment by armanozak** [comment] 2020-10-09 12:42
Hi @Carniatto,

How do we select `baz` when the state model is as follows:

```ts
interface SomeStateModel {
    foo: {
        bar: {
            baz: string;
        };
    };
}
```

Please take a look at [the updated playground](https://stackblitz.com/edit/ngxs-state-slice?file=src%2Fapp%2Fapp.state.ts). I believe you will find it valuable.

**Comment by richarddavenport** [comment] 2020-10-10 16:26
@armanozak @Carniatto I left the same feedback/question in the slack channel. I looked at possibly using something like lodash's get method to possibly selected deeply nested properties. Not sure how to implement it though.

**Comment by richarddavenport** [comment] 2020-10-21 00:11
@armanozak I think I figured it out.
https://stackblitz.com/edit/ngxs-state-slice-af6qas?file=src%2Fapp%2Fapp.state.ts

The idea is to just keep creating selectors from the property selectors initially made. It's working really well for me so far.

**Comment by armanozak** [comment] 2020-10-21 05:59
Hi @richarddavenport,

This does not look practical. It is a lot of work for not so much of a gain. Besides, you will end up creating selectors that you will never use anywhere (other than within the same state class).

**Comment by Carniatto** [comment] 2020-10-21 12:26
> Hi @richarddavenport,
> 
> This does not look practical. It is a lot of work for not so much of a gain. Besides, you will end up creating selectors that you will never use anywhere (other than within the same state class).

I believe creating selectors that are only used in the state class is not a bad practice. Matter of fact I'd encourage using this to promote smaller and easier to test selectors.

About the necessity to deeply create slices, I believe that's not the purpose of these helpers and it can be achieved using `createSelector` instead.

**Comment by richarddavenport** [comment] 2020-10-21 17:17
@armanozak  It's funny to me, but `creating selectors that you will never use anywhere (other than within the same state class).` actually sounds like the practical approach.

I understand the desire to reduce the number of selectors and to only have as many as you may need, and by using this approach I went from 14 selectors (all of them used) to 4 selectors.

_before_
``` typescript
public static getSlice(property: keyof RaterQuoteFormStateModel) {
    return createSelector([RATER_QUOTE_FORM_STATE_TOKEN], (state: RaterQuoteFormStateModel) => state[property]);
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getYear(form: RaterQuoteFormModel) {
    return form.year;
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getDealerCode(form: RaterQuoteFormModel) {
    return form.dealerCode;
  }

  @Selector([RaterQuoteFormState._getDealerCode])
  public static getDealerCode(dealerCode: string) {
    return dealerCode;
  }

  @Selector([RaterQuoteFormState.getSlice('errors')])
  public static getQuoteResponseErrors(errors: RaterQuoteFormErrors) {
    return errors.quoteResponse;
  }

  @Selector([RaterQuoteFormState._getYear])
  public static getYear(year: string) {
    return year;
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getMake(form: RaterQuoteFormModel) {
    return form.make;
  }

  @Selector([RaterQuoteFormState._getMake])
  public static getMake(make: string) {
    return make;
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getVin(form: RaterQuoteFormModel) {
    return form.vin;
  }

  @Selector([RaterQuoteFormState._getVin])
  public static getVin(vin: string) {
    return vin;
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  public static getMileage(form: RaterQuoteFormModel) {
    return form.mileage;
  }

  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getModel(form: RaterQuoteFormModel) {
    return form.model;
  }

  @Selector([RaterQuoteFormState._getModel])
  public static getModel(model: string) {
    return model;
  }

  @Selector([
    RaterQuoteFormState.getVin,
    RaterQuoteFormState.getYear,
    RaterQuoteFormState.getMake,
    RaterQuoteFormState.getModel,
  ])
  public static getVehicleFormInfo(vin: string, year: string, make: string, model: string) {
    return { vin, year, make, model };
  }
```

_after_
``` typescript
public static props = createPropertySelectors(RATER_QUOTE_FORM_STATE_TOKEN);
  public static formProps = createPropertySelectors(RaterQuoteFormState.props.form) as PropertySelectors<RaterQuoteFormModel>;
  public static errorProps = createPropertySelectors(RaterQuoteFormState.props.errors) as PropertySelectors<RaterQuoteFormErrors>;

  @Selector([
    RaterQuoteFormState.formProps.vin,
    RaterQuoteFormState.formProps.year,
    RaterQuoteFormState.formProps.make,
    RaterQuoteFormState.formProps.model,
  ])
  public static getVehicleFormInfo(vin: string, year: string, make: string, model: string) {
    return { vin, year, make, model };
  }
```

So, while it may seem at first like `a lot of work for not so much of a gain`, that is not the case for me and actually the opposite (less work, less code, more gain). Maybe for you though... but I'd encourage you to try it.

As a side note, the reason I have private selectors is that it is my attempt at creating an optimized selector:

``` typescript
  // this is not optimized enough for me... I don't want this selector to evaluate anytime the form changes
  @Selector([RaterQuoteFormState.getSlice('form')])
  private static _getMake(form: RaterQuoteFormModel) {
    return form.make;
  }

  // this will only evaluate if make has changed, not the entire form.
  @Selector([RaterQuoteFormState._getMake])
  public static getMake(make: string) {
    return make;
  }
```
So far I have noticed that the potentially new property selectors are optimized, so that is another reason to continue to try this new approach.

**Comment by armanozak** [comment] 2020-10-21 17:40
> > Hi @richarddavenport,
> > This does not look practical. It is a lot of work for not so much of a gain. Besides, you will end up creating selectors that you will never use anywhere (other than within the same state class).
> 
> @armanozak
> 
> I believe creating selectors that are only used in the state class is not a bad practice. Matter of fact I'd encourage using this to promote smaller and easier to test selectors.
> 
> About the necessity to deeply create slices, I believe that's not the purpose of these helpers and it can be achieved using `createSelector` instead.

Well, everything “can be achieved using `createSelector`”. That is not the point, isn’t it?

Never mind. You have asked about my opinion and here it is: Selecting only the first level of properties is definitely not worth discussing. So, please proceed as you prefer.

**Comment by markwhitfeld** [comment] 2020-10-21 20:25
I'll just add my 2c here 😉 
I think that the first step is to reduce the first level selectors that I have seen proliferating many apps. It is not meant to solve all cases, but rather to provide a convenient helper to reduce the number of selectors that look exactly the same other than a slight change in the name of the property being looked up.
All of these build upon `createSelector` so it is true that you can build anything with that 👍.
Our apps have vastly different needs and here we are trying to address the most common basic need to slice up the state into smaller selectors that through memoization will give a great tool for optimising your composite selectors.
Also, as a side note, that the `createPropertySelectors` creates a proxy that will create selectors as you access them, so technically it doesn't create any selectors that you don't use.

I think that the topic of deep selectors is a separate one to what is being proposed here.
That is not to say that it is not a valid topic to discuss 😄! Although we are encouraged to keep our states as flat as possible it is not always practical or feasible. Selecting deep properties can be another challenge in itself. There are some ideas that I am playing with that will allow for the dynamic creation of deep selectors from any part of an object graph, but I think that would definitely be a labs project.

I hope that this makes sense and thank you so much for all the feedback and ideas!!!
This can only improve with more feedback

**Comment by markwhitfeld** [comment] 2020-10-21 20:37
@richarddavenport Just a further optimisation you could make to your code with the other proposed selectors:
_Before:_
```
  public static props = createPropertySelectors(RATER_QUOTE_FORM_STATE_TOKEN);
  public static formProps = createPropertySelectors(RaterQuoteFormState.props.form) as PropertySelectors<RaterQuoteFormModel>;
  public static errorProps = createPropertySelectors(RaterQuoteFormState.props.errors) as PropertySelectors<RaterQuoteFormErrors>;

  @Selector([
    RaterQuoteFormState.formProps.vin,
    RaterQuoteFormState.formProps.year,
    RaterQuoteFormState.formProps.make,
    RaterQuoteFormState.formProps.model,
  ])
  public static getVehicleFormInfo(vin: string, year: string, make: string, model: string) {
    return { vin, year, make, model };
  }
```
_After (using `createMappedSelector`):_
```
  public static props = createPropertySelectors(RATER_QUOTE_FORM_STATE_TOKEN);
  public static formProps = createPropertySelectors(RaterQuoteFormState.props.form) as PropertySelectors<RaterQuoteFormModel>;
  public static errorProps = createPropertySelectors(RaterQuoteFormState.props.errors) as PropertySelectors<RaterQuoteFormErrors>;

  public static getVehicleFormInfo = createMappedSelector({
    vin: RaterQuoteFormState.formProps.vin,
    year: RaterQuoteFormState.formProps.year,
    make: RaterQuoteFormState.formProps.make,
    model: RaterQuoteFormState.formProps.model
  });
```
_After (using `createPickSelector`):_
```
  public static props = createPropertySelectors(RATER_QUOTE_FORM_STATE_TOKEN);
  public static formProps = createPropertySelectors(RaterQuoteFormState.props.form) as PropertySelectors<RaterQuoteFormModel>;
  public static errorProps = createPropertySelectors(RaterQuoteFormState.props.errors) as PropertySelectors<RaterQuoteFormErrors>;

  // note that this doesn't even make use of your formProps selector, and achieves the same optimised selector!
  public static getVehicleFormInfo = createPickSelector(RaterQuoteFormState.props.form, ['vin', 'year', 'make', 'model']);
```
Thanks for the example to try this out on!

**Comment by markwhitfeld** [comment] 2023-03-09 11:30
These are finally landing in the next release!
See PR: https://github.com/ngxs/store/pull/1824

**Comment by markwhitfeld** [comment] 2023-03-29 14:13
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.

**Closed by markwhitfeld** 2023-03-29 14:13 UTC
Labels: ready to release, type: feature, state: has PR, released
