### ISSUE TITLE
🐞[BUG]: Angular 14 - You have forgotten to import the NGXS module!

### ISSUE THREAD

**Issue by XardasLord** [ngxs/store#1859] opened 2022-06-15 12:50 UTC
### Affected Package
"@ngxs/store": "^3.7.4"
"@angular/core": "^14.0.2 (upgraded from v13)

### Is this a regression?
It worked fine before upgrading Angular 13 to 14

### Description
I'm getting this error when I open a modal (Angular Material Dialog) then close it and then open the dialog again. It used to work before Angular upgrade to 14. I have properly imported NGXS module for root and for feature.

```
ERROR Error: You have forgotten to import the NGXS module!
    at throwSelectFactoryNotConnectedError (ngxs-store.js:73:11)
    at createSelectObservableIvy (ngxs-store.js:3844:34)
    at createSelectObservable (ngxs-store.js:3800:11)
    at ngxs-store.js:3931:36
    at doInnerSub (mergeInternals.js:19:19)
    at outerNext (mergeInternals.js:14:57)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at ReplaySubject._subscribe (ReplaySubject.js:31:24)
    at ReplaySubject._trySubscribe (Observable.js:37:25)
```

The dialog opens logic looks like the following:
```
constructor(private zone: NgZone) { }

@Action(OpenFilterDialog)
openFilterDialog(_: StateContext<TodoStateModel>, __: OpenFilterDialog): MatDialogRef<TodoFilterDialogComponent> {
	return this.zone.run(() => (this.filterDialogRef = this.dialog.open(TodoFilterDialogComponent, this.filterDialogConfig)));
}
```

And in the TodoFilterDialogComponent component I use a `@Select`:
```
@Select(DictionaryState.getDictionary)
public enumDictionary$!: Observable<EnumDictionary>;
```

## 🔥 Exception or Error
<pre>```
ERROR Error: You have forgotten to import the NGXS module!
    at throwSelectFactoryNotConnectedError (ngxs-store.js:73:11)
    at createSelectObservableIvy (ngxs-store.js:3844:34)
    at createSelectObservable (ngxs-store.js:3800:11)
    at ngxs-store.js:3931:36
    at doInnerSub (mergeInternals.js:19:19)
    at outerNext (mergeInternals.js:14:57)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at ReplaySubject._subscribe (ReplaySubject.js:31:24)
    at ReplaySubject._trySubscribe (Observable.js:37:25)
```<code>
</code>
</pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 14.0.2
- @ngxs/store version: 3.7.4
<!-- Check whether this is still an issue in the most recent Angular version -->

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by arturovt** [comment] 2022-06-15 14:38
I'll close it since it's a duplicate of #1854. It's easier to track it within a single issue.

**Closed as completed by arturovt** 2022-06-15 14:38 UTC
