### ISSUE TITLE
🐞[BUG]: State updated once, but received two emits on @Select

### ISSUE THREAD

**Issue by Beef-Tech** [ngxs/store#1747] opened 2021-05-10 11:04 UTC
### Affected Package
The issue is caused by package @ngxs/store

### Is this a regression?
Don't know.

### Description

I've 3 states (A, B, C), with identical structure, like (i'm calling that '**Entity**' :
<pre><code>
{ id: string[], entities: T[] }`
</code></pre>

I need to update C with actions, and also whenever state A, or B change.

So I'm using Selectors for states A and B like that ; 
<pre><code>
@Select() public stateB$: Observable<Entity>`
</code></pre>

And I've created a subscription in a ngxOnInit to correctly update state C.
<pre><code>
combineLatest([ this.stateListener$,
                                             this.stateA$,
                                             this.stateB$
    ]).subscribe( (datas) => // do stuff and process ctx.setState(...));
</code></pre>
I'm listening to state C in Angular component via `@Select() public stateC$: Observable<Entity>`.

It seems to works well because state C is correctly updated (i saw it in redux-plugin devtools), but I always have two emits in my Angular component : 

_Subscriber.js:183 {id: "EUR_EUROCP", currency: "EUR", program: "EUROCP", isECP: true, isAvailable: true, …}
Subscriber.js:183 {id: "EUR_EUROCP", currency: "EUR", program: "EUROCP", isECP: true, isAvailable: true, …}_

## 🔬 Minimal Reproduction

- Create 2 or 3 states
- Link at least one to the third, by listening on state changes on ngxsOnInit, and update a property depending on other states (like number or boolean)
- Update a "sub"state and the "parent" state will be correctly updated, but the listener will be updated twice

## 🔥 Exception or Error
// Nope

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.12
- @ngxs/store version: 3.7.1

Browser:
- [ ] Chrome (desktop) version 90.0.4430.93
 
For Tooling issues:
- Node version: v12.22.1
- Platform:  Ubuntu
</code></pre>

**Comment by splincode** [comment] 2021-05-11 07:31
please create minimal reproduce on stackblitz or github

**Comment by Beef-Tech** [comment] 2021-05-14 14:26
Hello @splincode ,

I've made a sample app (lightweight version of mine) for my problem here : [https://stackblitz.com/edit/ngxs-store-update-twice-gbkktd?file=src/app/directory.state.ts](url)

The main goal is to update "Directory" when any "Person" is updated. (In my real-life case my state is linked with 3 states)

Click on "toggle" for first person.

If you check on DevTools you'll see that the state is correctly updated to true.
But if you check in the console (i've added one into the app.component.ts), you'll see that there is two emits :
- First is correct (containing the update)
- Second is incorrect (and should not be emitted - not related to any action)

Thanks.

**Comment by Beef-Tech** [comment] 2021-05-14 14:30
If it could helps, actually I've found a workaround : I dispatch an action to update the state (and it works perfectly...but have some impacts on app's perfromances - a little bit laggy).

**Comment by Beef-Tech** [comment] 2021-05-27 07:24
Hello, doest everyone have seen my update ?
Thanks.

**Comment by markwhitfeld** [comment] 2021-05-27 10:16
Hi @Beef-Tech, I am glad that you were able to find a workaround.
I had a look at your sample and it is possible that the double update is caused by your stateListener$ mechanism.

The source of the double emit is inside the rxjs mechanisms. Basically you are changing the state being represented by a BehaviorSubject while the behavior subject is being updated. This causes the distinctUntilChanged operator to get its' behavior wrong.

You really shouldn't be updating the state in response to a selector. NGXS has safeguards to get around this, but, unfortunately, you have found a way around it! By dispatching an action to fix the issue, you essentially scheduled the directory state update after the person update was finished. A very small demonstration of a hack to fix the issue in your stackblitz is to add a delay to your `personState$` observable. Eg:
![image](https://user-images.githubusercontent.com/1948265/119808473-71713e80-bee4-11eb-8fdf-20d94b71b017.png)

This `delay(0)` ensures that the directories update happens after the person state is finished emitting its changes.

That being said, I do really think that you should reconsider the way that you are using ngxs to do updates through the `ctx` of ngxsOnInit. The `ctx` in ngxsOnInit is not really designed to be used as a long-running mechanism for updating the state (here lies your workaround to the ngxs safeguards), but each @Action hander receives its own `ctx` in order to do its respective updates. This will most definitely break in future versions of NGXS where things will be stricter on the lifetime of the `ctx` object.

I also think that if you have a state that is being derived from other states, then that is probably better done through selectors which combine selectors from the two states.
I would also suggest that you look into state operators and the creation of custom state operators (see https://www.ngxs.io/advanced/operators#custom-operators) because I think that they will be a great help in getting the reuse that you seem to be trying to achieve.

Closing this because it is not an NGXS issue.

**Closed** 2021-05-27 10:16 UTC

**Comment by splincode** [comment] 2021-05-27 10:49
@markwhitfeld maybe convert issue to discussion for best example?

**Comment by markwhitfeld** [comment] 2021-05-28 07:44
@splincode I don't think it would be particularly useful, because this is a very odd usage of our lib that caused an uncommon side effect.

**Comment by Beef-Tech** [comment] 2021-05-30 23:44
Hi @markwhitfeld and @splincode, thank you for your check.
I didn't realize how my workaround wasn't a best practice.
I'll try to brainstorm my solution because I really need to perform what I call "additional computations" every time related state (and sometimes others) change.

**Comment by markwhitfeld** [comment] 2021-05-31 09:59
This should most definitely be handled as a selector, and should not copy data between states.
Have a look at [joining selectors](https://www.ngxs.io/concepts/select#joining-selectors), [Meta Selectors](https://www.ngxs.io/concepts/select#meta-selectors) (I like to call these Query classes), or even use `createSelector` to define a selector wherever you need to (can be inside a class or as an exported function).
